enactjs/agate

Switch/Switch.js
Switch/Switch.less
Switch/package.json
SwitchItem/SwitchItem.js
SwitchItem/SwitchItem.less
styles/colors-carbon.less
styles/colors-titanium.less

Just to make it go by faster I didn't end up using Item. Too many skinnable and spotlight things to think about.
Issue #12

Added Switch and SwitchItem

---

SwitchItem/SwitchItem.js

This allows the use of custom `offText` and `onText` strings

customize toggle text

---

IconItem/IconItem.js
IconItem/IconItem.less
Item/Item.less
LabeledItem/LabeledItem.js
LabeledItem/LabeledItem.less
styles/colors-carbon.less
styles/colors-titanium.less
styles/rules.less

Update styles and dependencies; clear out some cruft.
For carbon skin, I've added the gradient background for consistency.

Item, LabeledItem, IconItem refactor

---

Icon/Icon.js
Icon/IconList.js
Input/util.js
LabeledIcon/LabeledIcon.js
LabeledIconButton/LabeledIconButton.js
ToggleButton/ToggleButton.js

clean up agate docs and refer to agate instead of moonstone

cleanup agate docs

---

ColorPicker/ColorPicker.js
ColorPicker/ColorPicker.less
ColorPicker/package.json
styles/variables-carbon.less
styles/variables-titanium.less

Choose any color you like! The color comes back as `value`, like any other input.

Added ColorPicker

---

DateTimePicker/DateTimePicker.js
DateTimePicker/DateTimePicker.less
IconItem/IconItem.less
LabeledItem/LabeledItem.js
LabeledItem/LabeledItem.less
Picker/Picker.less
Popup/Popup.js
Popup/Popup.less

Updated layout with `DateTimePicker` and fixed some minor issues with `IconItem` and `LabeledItem`.
Fixes https://github.com/enactjs/agate-apps/issues/31

Clean up css and DateTimePicker layout

---

Button/Button.js
Button/Button.less

Added a "joined" state for Buttons to support more elaborate interfaces.
Also included documentation for props with missing docs in `Button.js`.

Joined Buttons

---

AgateDecorator/AgateDecorator.js
styles/colors-carbon.less
styles/colors-titanium.less
styles/rules.less

Added the ability for a user to customize the colors of a skin.

User-customizable skin colors

---

AgateDecorator/AgateDecorator.js
Button/Button.js
Button/Button.less
ColorPicker/ColorPicker.less
DateTimePicker/DateTimePicker.js
DateTimePicker/DateTimePicker.less
IncrementSlider/IncrementSlider.js
IncrementSlider/IncrementSlider.less
Input/Input.less
LabeledIconButton/LabeledIconButton.less
Panels/TabbedPanels.js
Panels/TabbedPanels.less
Picker/Picker.js
Picker/Picker.less
Popup/Popup.less
Skinnable/Skinnable.js
Slider/Slider.js
Slider/Slider.less
SliderButton/SliderButton.js
SliderButton/SliderButton.less
Switch/Switch.less
ToggleButton/ToggleButton.less
styles/colors-carbon.less
styles/colors-electro.less
styles/colors-titanium.less
styles/mixins.less
styles/skin.less
styles/variables-carbon.less
styles/variables-electro.less
styles/variables-titanium.less

- Adding Electro theme based on the design https://dribbble.com/shots/4277009-Electro.
- Also refactored a lot of the components to making theming easier
- Git checkout `feature/electro-skin-support` for `agate-apps` and run sampler to see the theme/skin (https://github.com/enactjs/agate-apps/pull/63)
- https://github.com/enactjs/agate/issues/58
Electro inspiration
Preview of Electro theme:

Theme: Electro

---

Button/Button.less
ToggleButton/ToggleButton.js
ToggleButton/ToggleButton.less
styles/colors-carbon.less
styles/colors-electro.less
styles/colors-titanium.less
styles/variables-carbon.less
styles/variables-electro.less
styles/variables-titanium.less

Added more means of customizing `ToggleButton` as well as standardized the terminology used for the LESS variables that govern it.

Tidy the LESS rules for ToggleButton

---

DropManager/DropManager.js
DropManager/DropManager.less
Rearrangeable/Rearrangeable.js

Each slot can now define relevant information about itself, for the widgets to respond to.

Updated Draggable to support container shape metadata

---

GridListImageItem/GridListImageItem.js
GridListImageItem/GridListImageItem.less
Image/Image.js
Image/Image.less
Image/package.json
Panels/Panels.js

* Added agate/Image, upgraded all components to use it
* Fixed a PropType issue with Panels and GridListImageItem
Signed-off-by: Blake Stephens <blake.stephens@lge.com>

ENYO-5737: Added agate/Image, Fixed PropTypes bugs

---

RadioItem/RadioItem.js
RadioItem/RadioItem.less
RadioItem/package.json
styles/colors-carbon.less
styles/colors-electro.less
styles/colors-titanium.less
styles/variables-carbon.less
styles/variables-electro.less
styles/variables-titanium.less

This adds `agate/RadioItem` for a simple radio toggle.

PLAT-71035: User selection screen inside home screen:  replace on/off toggles with something more intuitive

---

TabGroup/TabGroup.js

Enact-DCO-1.0-Signed-off-by: Stephen Choi <stephen.choi@lge.com>

PLAT-71670: Set selected state to Group

---

styles/colors-copper.less

Enact-DCO-1.0-Signed-off-by: Stephen Choi <stephen.choi@lge.com>

PLAT-71625: Increase brightness of copper theme accent color

---

Panels/Panel.js

Signed-off-by: Blake Stephens <blake.stephens@lge.com>

PLAT-71791: Added `css` customizability to `Panel`

---

Drawer/Drawer.less
Item/Item.less
LabeledItem/LabeledItem.less
Switch/Switch.js
Switch/Switch.less
SwitchItem/SwitchItem.js
SwitchItem/SwitchItem.less
styles/colors-carbon.less
styles/colors-copper-day.less
styles/colors-copper.less
styles/colors-electro.less
styles/colors-titanium.less
styles/variables-carbon.less
styles/variables-copper-day.less
styles/variables-copper.less
styles/variables-electro.less
styles/variables-titanium.less

Not related to a ticket, per se, but was part of the new Copper Day theme.

Updated Drawer, tidy Switch

---

Skinnable/Skinnable.js
TabGroup/TabGroup.js
styles/colors-cobalt-day.less
styles/colors-cobalt.less
styles/skin.less
styles/variables-cobalt.less

To be merged with https://github.com/enactjs/agate-apps/pull/206
PLAT-71494 PLAT-71493

Cobalt and Cobalt Day Theme

---

Panels/Panels.js
html-template.ejs
package.json

Update dependencies to Enact 3.0 and upgrade Agate components.

PLAT-84218: Update Agate to Enact 3.0

---

Spinner/Spinner.js
Spinner/Spinner.module.less
Spinner/package.json
styles/colors-carbon.less
styles/colors-cobalt-day.less
styles/colors-cobalt.less
styles/colors-copper-day.less
styles/colors-copper.less
styles/colors-electro.less
styles/colors-titanium.less
styles/variables-carbon.less
styles/variables-cobalt.less
styles/variables-copper.less
styles/variables-electro.less
styles/variables-titanium.less

Add `Spinner` with `color` ("dark" and "light") and `size` ("small" and "medium") props.
Light Spinner
Dark Spinner

PLAT-84314: Add Searching Spinner

---

AgateDecorator/AgateDecorator.js
Button/Button.js
Button/Button.module.less
Skinnable/Skinnable.js
styles/colors-cobalt.less
styles/colors-gallium.less
styles/colors-titanium.less
styles/skin.less
styles/variables-gallium.less

Also updated applySkins to allow the assignment of a "base" skin, which other skins can leverage for overrides, so they don't all need to be updated when a single variable is added.

PLAT-84903: Add Galluim theme

---

Header/Header.js
Header/Header.module.less
Header/package.json
styles/variables-carbon.less
styles/variables-cobalt.less
styles/variables-copper.less
styles/variables-electro.less
styles/variables-titanium.less

Add basic Header with subtitle below and title above.
Sample: https://github.com/enactjs/agate-apps/pull/215

PLAT-84544: Add Header

---

data/ConsumerDecorator/ConsumerDecorator.js

PLAT-85428: Add support for mapStateToProps function

---

Heading/Heading.js
Heading/Heading.module.less
Heading/package.json
Heading/tests/Heading-specs.js
styles/colors-gallium.less
styles/variables-gallium.less

This adds a new Heading component, with primary working being added for the "title" size of the component.

PLAT-84726: Add Heading component

---

styles/colors-carbon.less
styles/colors-gallium-day.less
styles/colors-gallium-night.less
styles/colors-titanium.less

Clean up color variable cruft for input

PLAT-85816: Remove duplicate input color variable

---

Scrollable/ScrollButton.js
Scrollable/ScrollButtons.js
Scrollable/ScrollThumb.js
Scrollable/Scrollable.js
Scrollable/Scrollbar.js
Scrollable/Scrollbar.module.less
Scrollable/package.json
Scroller/Scroller.js
Scroller/package.json
styles/colors-carbon.less
styles/colors-cobalt-day.less
styles/colors-cobalt.less
styles/colors-copper-day.less
styles/colors-copper.less
styles/colors-electro.less
styles/colors-gallium-day.less
styles/colors-gallium.less
styles/colors-titanium.less

Adding the initial codebase for the `Scroller` component, allowing for 5way navigation to scroll contents into view.

Add Agate Scroller

---

data/ProviderDecorator/ProviderDecorator.js

Fix freeze logic to not try to freeze arrays

---

Scrollable/Scrollable.js

This change allows `Scroller` to disable/enable its spotlight container based on drag events that are emitted.
This change is dependent on another PR: https://github.com/enactjs/enact/pull/2572

PLAT-85707: Fixed Scroller to handle drag events

---

IconButton/IconButton.module.less
styles/colors-carbon.less
styles/colors-cobalt-day.less
styles/colors-cobalt.less
styles/colors-copper-day.less
styles/colors-copper.less
styles/colors-electro.less
styles/colors-gallium-day.less
styles/colors-gallium-night.less
styles/colors-titanium.less
styles/variables-gallium.less

Add `IconButton` border for `selected` prop.
10px border for size `huge` and 3px for the other sizes.

PLAT-85961: Add IconButton selected style

---

styles/colors-base.less
styles/variables-base.less

ENYO-6297: Define @agate-iconbutton-huge-border-width in variables-base.less

---

Item/Item.module.less
LabeledIcon/LabeledIcon.js
Panels/ApplicationCloseButton.js
Panels/Panel.module.less
RadioItem/RadioItem.js
RadioItem/RadioItem.module.less
Scrollable/ScrollButton.js
Spinner/Spinner.module.less
SwitchItem/SwitchItem.module.less
styles/colors-base.less
styles/colors-carbon.less
styles/colors-cobalt-day.less
styles/colors-cobalt.less
styles/colors-copper-day.less
styles/colors-copper.less
styles/colors-electro.less
styles/colors-gallium-day.less
styles/colors-gallium-night.less
styles/colors-titanium.less
styles/variables-base.less
styles/variables-gallium.less

Addresses some of Panels, Panel, Heading, and Item.

PLAT-85479: First wave of style updating to match the theme

---

Spinner/Spinner.js
Spinner/Spinner.module.less
styles/variables-base.less
styles/variables-carbon.less
styles/variables-cobalt.less
styles/variables-copper.less
styles/variables-electro.less
styles/variables-gallium.less
styles/variables-titanium.less

Starting from #151, I looked at ways of making the code a little easier to configure (and hopefully maintain). This version leverages fewer LESS variables and automatically and evenly spaces itself given the width of the parent container and an arbitrary amount of circles/dots. As for configuration, you simply set the number of circles, the width of the spinner area, and the duration of the animation. It respects and responds to arbitrary margins and paddings and always remains centered in its space regardless of the height.

PLAT-84609: Implement Spinner type "loading"

---

PopupMenu/PopupMenu.js
PopupMenu/PopupMenu.module.less
styles/variables-base.less
styles/variables-gallium.less

Add scrolling to `PopupMenu`, allowing scrollable elements in popup.

PLAT-85962: Add PopupMenu Support for Scrolling

---

Button/Button.js
Button/Button.module.less
Icon/Icon.module.less
Scrollable/Scrollbar.module.less
styles/colors-base.less
styles/variables-base.less
styles/variables-carbon.less
styles/variables-cobalt.less
styles/variables-copper.less
styles/variables-electro.less
styles/variables-gallium.less
styles/variables-titanium.less

- Add new sizes to the button component ( smallest and huge)
- Add new sizes to the Icon component ( smallest and huge)
- Reconciled IconButton component into Button component
- Updated the style for the new sizes

PLAT-88683 Iconbutton needs to be reconciled with Button with Icon component

---

Input/Input.module.less
styles/colors-base.less
styles/colors-carbon.less
styles/colors-cobalt-day.less
styles/colors-cobalt.less
styles/colors-copper-day.less
styles/colors-copper.less
styles/colors-electro.less
styles/colors-gallium-day.less
styles/colors-gallium-night.less
styles/colors-titanium.less
styles/variables-base.less

Need to adjust `Input` border and padding styles to better indicate the tappable area of the input.
Note: Need to identify the border colors for all skins/themes and whether to use the same colors as borders for other bordered components.

PLAT-95230: Adjust input border and padding styles

---

PopupMenu/PopupMenu.js

Getting props warnings when opening the profile screen.

Hotfix: Updated Scroller props

---

styles/variables-electro.less

Electro's icon-only button should be squarish, not roundish.

Corrected Electro's icon-button shape

---

Scrollable/ScrollButton.js
Scrollable/ScrollButtons.js

Fixed bug with ScrollButton not rendering properly with icon.

PLAT-97189: Fix ScrollButton to use icon prop

---

README.md

Add copyright and license information to Readme

PLAT-98217: Add Copyright and License

---

Button/Button.js

Revert "ENYO-6364: Restore compatibility with Enact 3.2.5"

---

README.md

Enact-DCO-1.0-Signed-off-by: Roy Sutton roy.sutton@lge.com

Update agate description in README

---

Button/Button.js
IncrementSlider/IncrementSliderButton.js
Scrollable/ScrollButton.js
Scrollable/ScrollButtons.js
Scrollable/ScrollThumb.js
Scrollable/Scrollable.js
Scrollable/Scrollbar.js
Scrollable/Scrollbar.module.less
Scrollable/useChild.js
Scrollable/useEvent.js
Scrollable/useScrollbar.js
Scrollable/useSpotlight.js
Scroller/Scroller.js
Scroller/useEvent.js
Scroller/useSpotlight.js
samples/sampler/stories/default/Icon.js
samples/sampler/stories/default/ItemKitchenSink.js

Migration of `Scroller` component based on a hook migration of `@enact/ui`.
- Removes overscroll effect in code level
- Covers following prior PRs: #130, #139, #145, #154 , #169 , #175, #180, #183 
Known Issues:
- ~~Sometimes stuttering occurs after scrolling.~~ Fixed by ui's patch
- ~~This PR requires ui's patch (https://github.com/enactjs/enact/pull/2690)~~  Fixed by ui's patch

PLAT-100348: Migration Scroller to use hooks

---

package.json
samples/sampler/package.json

Requires https://github.com/enactjs/cli/pull/208 for `enact clean --all` support
Ensures root `package.json` and sampler package.json` get up-to-date bootstrap, clean, cleanall run scripts.

PLAT-100998: Use updated CLI commands for bootstrap and clean

---

Scroller/Scroller.js
VirtualList/VirtualList.js
VirtualList/VirtualListBasic.js
VirtualList/usePreventScroll.js
VirtualList/useThemeVirtualList.js
useScroll/ScrollableBasic.js
useScroll/Scrollbar.module.less
useScroll/useEvent.js
useScroll/useScroll.js
useScroll/useThemeScrollContentHandle.js

The new prop scrollMode is added.
- 'translate': the scroll content is scrolled by CSS translate.
- 'native': the scroll content is scrolled by scrolltop (native way).

PLAT-101272: Add a new prop `scrollMode`

---

docs/agate.svg
docs/config.json

Enact-DCO-1.0-Signed-off-by: Roy Sutton roy.sutton@lge.com

Add agate image to repo

---

VirtualList/useThemeVirtualList.js

To resolve PLAT-103307, I'd like to revert the change made by PLAT-100713

PLAT-103307: Revert PLAT-100713

---

Scroller/useThemeScroller.js
useScroll/useEvent.js

Cleaned up code related scrollInfo that was removed from ENYO-5710

PLAT-102575: Clean up code related scrollInfo

---

Skinnable/Skinnable.js
samples/sampler/src/AgateEnvironment/AgateEnvironment.js
styles/colors-silicon-day.less
styles/colors-silicon-night.less
styles/skin.less
styles/variables-silicon.less

This includes a complement of style files (`styles` directory) which are slightly modified clones of the gallium files. A "Silicon" skin entry has been added to storybook sampler. Introductory inline documentation was added to each of the style files to help explain how to manage and maintain the contents.

PLAT-106369: Add "Silicon" skin, with day and night variants

---

Button/Button.js

PLAT-106355: Fix Button prop bleed for badgeColor

---

Scroller/useThemeScroller.js
VirtualList/useEvent.js
VirtualList/usePreventScroll.js
VirtualList/useSpotlight.js
VirtualList/useThemeVirtualList.js

Cleaned up useEffect dependencies for Scroller and VirtualList

PLAT-98222: Scroller: Clean up useEffect dependencies

---

useScroll/ScrollbarTrack.js

PLAT-109849: Fix not to show scrollbar on every re-render

---

Popup/Popup.js
Popup/tests/Popup-specs.js

Feature Added
Bug fixed on Popup component.
Comments
Removed unnecessary "centered" text from Popup. Updated tests.

FORTECH-53: Popup renders unnecessary text in body

---

Slider/Slider.js
Slider/Slider.module.less
samples/sampler/stories/default/Slider.js
styles/colors-base.less
styles/colors-silicon-day.less
styles/colors-silicon-night.less
styles/variables-base.less
styles/variables-carbon.less
styles/variables-electro.less
styles/variables-gallium.less
styles/variables-silicon.less

Feature Added
Added silicon styles for Slider

FORTECH-64 Add silicon styles for Slider

---

Picker/Picker.js
RangePicker/RangePicker.js
ThumbnailItem/ThumbnailItem.js
internal/Picker/Picker.js

Fix up a few doc errors
* Remove backticks from prop name
* Remove private HOCs
* Remove invalid pragma

PLAT-113733: Fix doc errors

---

styles/colors-gallium-day.less
styles/colors-gallium-night.less
styles/variables-gallium.less

Removed duplicate gallium variables

FORTECH-78: Removed duplicate gallium variables

---

Button/Button.js
TooltipDecorator/Tooltip.js
TooltipDecorator/Tooltip.module.less
TooltipDecorator/TooltipDecorator.js
TooltipDecorator/TooltipLabel.js
TooltipDecorator/package.json
TooltipDecorator/tests/TooltipDecorator-specs.js
TooltipDecorator/util.js
samples/sampler/stories/default/TooltipDecorator.js
styles/colors-base.less
styles/colors-gallium-day.less
styles/colors-silicon-day.less
styles/variables-base.less
styles/variables-gallium.less
styles/variables-silicon.less

Feature Added
Created Agate TooltipDecorator component.
Comments
Added new TooltipDecorator component in Agate. Created styles for Gallium and Silicon skins, added unit tests and integrated component in StoryBook, added tooltip as Button prop.

FORTECH-8: Add TooltipDecorator

---

VirtualList/VirtualList.js
VirtualList/useEvent.js
VirtualList/useSpotlight.js
VirtualList/useThemeVirtualList.js
useScroll/useEvent.js
useScroll/useScroll.js
useScroll/useSpotlight.js

This PR syncs up agate/VirtualList with sandstone/VirtualList.
Some of bug fixes from sandstone/VirtualList needs to be synced to agate/VirtualList.
Please refer to the ticket for details.

PLAT-115302: Sync up VirtualList

---

Scroller/Scroller.js
Scroller/useThemeScroller.js
samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js
samples/sampler/src/ThemeEnvironment/ThemeEnvironment.module.less
samples/sampler/stories/default/Scroller.js
samples/sampler/stories/default/VirtualList.js

This PR syncs up agate/Scroller with sandstone/Scroller .
Some of bug fixes from sandstone/Scroller needs to be synced to agate/Scroller .
Please refer to the ticket for details.

 PLAT-115303: Sync up with sandstone/Scroller

---

styles/variables-silicon.less

Fix for slider when pressing the slider knob, the part of the knob is clipped.

FORTECH-85: Slider knob is clipped when pressed

---

internal/DateComponentPicker/DateComponentPicker.module.less
styles/variables-base.less

Fix to compile JS documentation properly

FORTECH-108: Fix to compile JS documentation properly

---

AgateDecorator/AgateDecorator.js
Arc/Arc.js
Drawer/Drawer.js
Icon/Icon.js
Picker/Picker.js
PopupMenu/PopupMenu.js
Scroller/Scroller.js
Spinner/Spinner.js

Enact-DCO-1.0-Signed-off-by: Jeongran Jang <jeongran.jang@lge.com>
Some example code and tags are not working properly in enact docs.
Fix comments for AgateDecorator, Arc, Icon, Picker, Scroller, Spinner and Drawser
PLAT-104265

PLAT-104265: Fix comments for Documetation

---

DatePicker/DatePickerBase.js
TimePicker/TimePickerBase.js
internal/DateTime/DateTime.js
internal/Picker/Picker.js
internal/Picker/Picker.module.less

This PR fixes changed year picker width when the value is changing.

PLAT-119501: Fixed year picker width to not changing

---

Item/Item.module.less
styles/colors-base.less
styles/colors-gallium-day.less
styles/colors-silicon-day.less
styles/variables-base.less
styles/variables-gallium.less
styles/variables-silicon.less

Changes to Item's label styles to correspond to GUI design

FORTECH-114: Fixed Item's label position and color

---

PopupMenu/PopupMenu.js
Scroller/Scroller.js
VirtualList/VirtualList.js
samples/sampler/stories/default/PopupMenu.js
samples/sampler/stories/default/Scroller.js
samples/sampler/stories/default/VirtualGridList.js
samples/sampler/stories/default/VirtualList.js

Enact-DCO-1.0-Signed-off-by: Jeongran Jang (jeongran.jang@lge.com)
There are some unnecessary props
Remove those props in Agate and knobs in sampler;
- `orientation` prop for `PopupMenu`
- `noScrollByWheel` prop for `Scroller` and `VirtualList`
PLAT-122713

PLAT-122713:  Clean up unnecessary props for 1.0.0 Release

---

samples/sampler/stories/default/icons.js

Updated the icon list in sampler app for increment/decrement buttons based on te current list of available icons in Agate

PLAT-122788: Fixed Icon list for incrementSlider sampler

---

samples/sampler/stories/default/Input.js
samples/sampler/stories/default/icons.js

Converted "type" knob to a dropdown for Input story

PLAT-122790: Converted "type" knob to a dropdown for Input story

---

CHANGELOG.md
Item/Item.module.less
samples/sampler/stories/default/VirtualList.js
samples/sampler/stories/default/VirtualList.module.less
useScroll/Scrollbar.module.less

Issue 1: Item bottom border was hard to see on night mode.
Issue 2: Item selected bottom border didn't show.
Issue 3: The edge of the Item bottom border in gallium skin was triangle.
Issue 1: Changed item bottom border color.
Issue 2: Fixed item selected bottom border.
Issue 3: Fixed the edge of the Item bottom border in gallium skin.
PLAT-122724

PLAT-122724: Fixed VirtualList Item border to display properly

---

CHANGELOG.md
DateTimePicker/DateTimePicker.js

Agate - DateTimePicker story The latest 'value' of 'onChange' in 'Actions' should was same as the input.
Solution: add Changeable to DateTimePicker and synchronize the current value with inner TimePicker and DatePicker
PLAT-123179

PLAT-123179: DateTimePicker - Fixed returned value by onChange event

---

CHANGELOG.md
Keypad/Keypad.js

Keypad:
- used `@enact/core/handle/forward` to forward the onChange function
PLAT-124530

PLAT-124530: Not show console error when selecting any number in the Keypad

---

CHANGELOG.md
FanSpeedControl/FanSpeedControl.js
FanSpeedControl/FanSpeedControl.module.less
SliderButton/SliderButtonBehaviorDecorator.js
styles/variables-base.less
styles/variables-gallium.less
styles/variables-silicon.less
tests/screenshot/apps/components/FanSpeedControl.js

Issue: Text is not aligned in center if no icon in FanSpeedControl in sampler.
Solution: Added `noIcon` class to center text when there is no icon.
PLAT-124527

PLAT-124527: Fix text to be aligned in center if no icon in FanSpeedControl

---

tests/ui/apps/Item/Agate-Item-View.js
tests/ui/specs/Item/Agate-Item-specs.js
tests/ui/specs/Item/Agate-ItemPage.js

- Added UI tests for agate/Item
PLAT-126330

PLAT-126330: Add UI tests for agate/Item

---

package.json

- Added sampler-qa script in package.json
PLAT-126341

PLAT-126341: Added sampler-qa script in package.json

---

ArcPicker/ArcPicker.js
ArcPicker/ArcPickerBehaviorDecorator.js
DatePicker/DatePicker.js
DatePicker/DatePickerBase.js
DateTimePicker/DateTimePicker.js
Dropdown/Dropdown.js
FanSpeedControl/FanSpeedControl.js
MediaPlayer/MediaPlayer.js
MediaPlayer/util.js
TemperatureControl/TemperatureControl.js
TimePicker/TimePicker.js
TimePicker/TimePickerBase.js
internal/DateTime/DateTimeDecorator.js
useScroll/useScrollbar.js

This PR fixes isomorphic test failed Components from jenkins.
This PR is paired with enact PR https://github.com/enactjs/enact/pull/2873.
Test passed 636.

PLAT-127311: Fix isomorphic test failed components

---

tests/ui/apps/Button/Button-View.js
tests/ui/specs/Button/Button-specs.js
tests/ui/specs/Button/ButtonPage.js

- added UI tests for agate/Button
PLAT-126342

PLAT-126342: Add UI tests for agate/Button

---

ArcPicker/tests/ArcPicker-specs.js
tests/ui/apps/ArcPicker/ArcPicker-View.js
tests/ui/specs/ArcPicker/ArcPicker-specs.js
tests/ui/specs/ArcPicker/ArcPickerPage.js

- Added ui tests for ArcPicker
- Added unit tests for ArcPicker
PLAT-127669

PLAT-127669: Added ui and unit tests for ArcPicker

---

FanSpeedControl/tests/FanSpeedControl-specs.js
tests/ui/apps/FanSpeedControl/FanSpeedControl-View.js
tests/ui/specs/FanSpeedControl/FanSpeedControl-specs.js
tests/ui/specs/FanSpeedControl/FanSpeedControlPage.js

- Added ui tests for FanSpeedControl
- Added unit tests for FanSpeedControl
PLAT-128468

PLAT-128468: Add UI tests and unit tests for FanSpeedControl

---

WindDirectionControl/tests/WindDirectionControl-specs.js
tests/ui/apps/WindDirectionControl/WindDirectionControl-View.js
tests/ui/specs/WindDirectionControl/WindDirectionControl-specs.js
tests/ui/specs/WindDirectionControl/WindDirectionControlPage.js

- Added ui tests for WindDirectionControl
- Added unit tests for WindDirectionControl
PLAT-128503

PLAT-128503: Add UI tests and unit tests for WindDirectionControl

---

tests/ui/apps/TemperatureControl/TemperatureControl-View.js
tests/ui/specs/TemperatureControl/TemperatureControl-specs.js
tests/ui/specs/TemperatureControl/TemperatureControlPage.js

- Added ui tests for TemperatureControl
PLAT-128500

PLAT-128500: Added UI tests for TemperatureControl

---

Drawer/tests/Drawer-specs.js
tests/ui/apps/Drawer/Drawer-View.js
tests/ui/specs/Drawer/Drawer-specs.js
tests/ui/specs/Drawer/Drawer-utils.js
tests/ui/specs/Drawer/DrawerPage.js

- added unit tests for agate/Drawer
- added UI tests for agate/Drawer
PLAT-128457

PLAT-128457: Add UI tests and unit tests for Drawer

---

tests/ui/apps/IncrementSlider/IncrementSlider-View.js
tests/ui/specs/IncrementSlider/IncrementSlider-specs.js
tests/ui/specs/IncrementSlider/IncrementSliderPage.js

- Added ui tests for IncrementSlider
PLAT-128478

PLAT-128478: Added UI tests for IncrementSlider

---

ArcPicker/ArcPicker.js
ArcPicker/ArcPickerBehaviorDecorator.js
DatePicker/DatePicker.js
DatePicker/DatePickerBase.js
DateTimePicker/DateTimePicker.js
Dropdown/Dropdown.js
FanSpeedControl/FanSpeedControl.js
MediaPlayer/MediaPlayer.js
MediaPlayer/util.js
TemperatureControl/TemperatureControl.js
TimePicker/TimePicker.js
TimePicker/TimePickerBase.js
internal/DateComponentPicker/DateComponentPicker.js
internal/DateTime/DateTimeDecorator.js
internal/Picker/Picker.js
useScroll/useScrollbar.js

This PR fixes isomorphic test failures.

PLAT-129116: Fix isomorphic test failures

---

ThumbnailItem/tests/ThumbnailItem-specs.js
tests/ui/apps/ThumbnailItem/ThumbnailItem-View.js
tests/ui/apps/ThumbnailItem/ThumbnialItem-View.js
tests/ui/specs/ThumbnailItem/ThumbnailItem-specs.js
tests/ui/specs/ThumbnailItem/ThumbnailItemPage.js

- Added ui tests for ThumbnailItem
- Updated unit tests for ThumbnailItem
PLAT-128501

PLAT-128501:  Add UI tests and unit tests for ThumbnailItem

---

tests/ui/apps/TooltipDecorator/TooltipDecorator-View.js
tests/ui/specs/TooltipDecorator/TooltipDecorator-specs.js
tests/ui/specs/TooltipDecorator/TooltipDecoratorPage.js

- added UI tests for agate/TooltipDecorator
PLAT-128502

PLAT-128502: Add UI tests for TooltipDecorator

---

ImageItem/tests/ImageItem-specs.js
tests/ui/apps/ImageItem/ImageItem-View.js
tests/ui/specs/ImageItem/ImageItem-specs.js
tests/ui/specs/ImageItem/ImageItemPage.js

- Added ui tests for ImageItem
- Updated unit tests for ImageItem
PLAT-128472

PLAT-128472: Add UI/unit tests for ImageItem

---

Scroller/tests/Scroller-specs.js
tests/ui/apps/Scroller/Scroller-View.js
tests/ui/apps/Scroller/WithSpottable/ScrollerWithSpottable-View.js
tests/ui/specs/Scroller/Scroller-nativeScroll-specs.js
tests/ui/specs/Scroller/Scroller-translateScroll-specs.js
tests/ui/specs/Scroller/ScrollerPage.js
tests/ui/specs/Scroller/WithSpottable/ScrollerWithSpottable-specs.js

- added unit tests for agate/Scroller
- added UI tests for agate/Scroller
PLAT-129514

PLAT-129514: Add UI tests and unit tests for Scroller

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE.md
.github/ISSUE_TEMPLATE/SUPPORT.md
.github/PULL_REQUEST_TEMPLATE.md

This PR adds a PR template and Issues template for agate repo.

Add a PR template

---

Heading/tests/Heading-specs.js

- Added one unit test for `Heading`
PLAT-129508

PLAT-129508: Add unit test for Heading

---

.travis.yml
CheckboxItem/CheckboxItem.js
internal/Picker/Picker.js
package.json

Reverts enactjs/agate#202 because of UI test failed

Revert "Add docs validation to Travis"

---

samples/sampler/package.json

Add dependencies for agate's samplers

PLAT-130814:Need to fix 'enact-nebula-samplers' jenkins job fail

---

RadioItem/tests/RadioItem-specs.js

- Added more unit tests for `RadioItem`
PLAT-129513

PLAT-129513: Add unit tests for RadioItem

---

.github/PULL_REQUEST_TEMPLATE.md

Add check items for  test and docs

Add check items on PR template

---

tests/ui/specs/Drawer/Drawer-specs.js

Enact-DCO-1.0-Signed-off-by: Dongsu Won (dongsu.won@lgepartner.com)
- Need to add delay for Draw UI-Test(Jenkins Fail).
- Add delay for Draw UI-Test.
[//]:# (Related issues, references)
PLAT-132784

PLAT-132784: Fix ui-test fail on Drawer

---

README.md

Need to explain how to create Agate App
Add example in the readme.md
Enact-DCO-1.0-Signed-off-by: Seungho Park <seunghoh.park@lge.com>

PLAT-133997: Add creating agate app example in the readme.md

---

FanSpeedControl/FanSpeedControl.js
MediaPlayer/MediaPlayer.js

- FanSpeedControl and MediaPlayer did not have required tags in documentation
- Added missing required tags to FanSpeedControl and MediaPlayer documentation
PLAT-123303
Enact-DCO-1.0-Signed-off-by: Paul Beldean paul.beldean@lgepartner.com

PLAT-123303: [Agate][Docs] FanSpeedControl and MediaPlayer: Add required tags for documentation

---

.github/PULL_REQUEST_TEMPLATE.md

Remove empty line on PR Template to reduce margin between each checklist

Remove empty line on PR Template

---

.travis.yml

Recently, we updated Lerna version for Enact from 2.x to 4. Due to a breaking change from Lerna 3, Travis CI test for this library does not work properly.
Also, we're using node 10 for Travis CI and it looks better to use LTS version of node for long-term testing.
Update node version to LTS and update a Lerna option in .travis.yml.
PLAT-139487

PLAT-139487: Update travis CI configuration

---

tests/screenshot/apps/components/Button.js

In the Agate Button screenshot test, the focus TC is same with normal. so it return failed
Change title to prevent duplicate names of output files.
I was tried to assign a indicator on all `focus:true` test cases like `locale`. But I have failed :(.
PLAT-139175

PLAT-139175: Change focused button screenshot name

---

tests/ui/specs/Item/Item-specs.js

Enact-DCO-1.0-Signed-off-by: Dongsu Won (dongsu.won@lgepartner.com)
- Need to fix ui-test for Item component.
- Fix ui-test for Item component.
[//]:# (Related issues, references)
PLAT-139790
Failures that occur in Initial Condition cannot find the exact cause and will be worked on the next ticket.

PLAT-139790  Fix ui-test fail on Jenkins

---

ArcPicker/ArcPicker.js

Must be fixed isomorphic test fails
Check Jenkins full log for fail cases and fix it
PLAT-141518

PLAT-141518: Fix isomorphic test fails

---

CHANGELOG.md
samples/sampler/stories/default/Scroller.js
styles/colors-cobalt-day.less

On Cobalt skin, slider's background-color was hardly visible, so I changed the color variable with a lighter shade.
PLAT-141635

PLAT-141635: Fixed Slider background-color on Cobalt skin

---

CHANGELOG.md
styles/colors-base.less
styles/colors-carbon.less
styles/colors-cobalt-day.less
styles/colors-cobalt.less
styles/colors-copper-day.less
styles/colors-copper.less
styles/colors-electro.less
styles/colors-silicon-day.less
styles/colors-silicon-night.less
styles/colors-titanium.less

ScrollerThumb is not very visible on Carbom, Cobalt, Copper, Electro, Titanium skins
Changed color of ScrollerThumb to a more visible one
PLAT-141480

PLAT-141480: Scroller - scrollbar is not very visible

---

.travis.yml
ContextualPopupDecorator/tests/ContextualPopupDecorator-specs.js
Image/Image.js
MediaPlayer/MediaPlayer.js
Panels/tests/BreadcrumbDecorator-specs.js
Panels/tests/Panels-specs.js
Popup/PopupState.js
ThumbnailItem/ThumbnailItem.js
VirtualList/tests/VirtualList-specs.js
VirtualList/useThemeVirtualList.js
samples/qa-a11y/src/views/ArcPicker.js
samples/qa-a11y/src/views/VirtualGridList.js
samples/qa-a11y/src/views/VirtualList.js
tests/screenshot/apps/Agate-View.js
tests/screenshot/apps/components/VirtualList.js
tests/ui/apps/VirtualList/VirtualGridList/VirtualGridList-View.js
tests/ui/apps/VirtualList/VirtualList/VirtualList-View.js
tests/ui/apps/VirtualList/VirtualList/VirtualListInPanels-View.js
tests/ui/specs/ColorPicker/ColorPicker-specs.js
tests/ui/specs/Dropdown/Dropdown-specs.js
tests/ui/specs/Dropdown/InScroller/DropdownInScroller-specs.js

Enyo-5941 : Fix --report-unused-disable-directives warnings and enable for Travis

---

ColorPicker/tests/ColorPicker-specs.js
ContextualPopupDecorator/tests/ContextualPopupDecorator-specs.js
Drawer/tests/Drawer-specs.js
Scroller/tests/Scroller-specs.js

Migrated tests from Enzyme to Testing Library.
Changed test structure to work with Testing Library.
WRN-4397

WRN-4397: Migrate ColorPicker, ContextualPopupDecorator, Drawer and Scroller unit tests to Testing Library.

---

Panels/tests/Breadcrumb-specs.js
Panels/tests/BreadcrumbDecorator-specs.js
Panels/tests/Panels-specs.js
ThemeDecorator/tests/ThemeDecorator-specs.js
VirtualList/tests/VirtualList-specs.js

Migrated `Panels/Breadcrumb`, `Panels/BreadcrumbDecorator`, `Panels/Panels`, `ThemeDecorator` and `VirtualList` unit tests to Testing Library
WRN-4406

WRN-4406: [Agate] Migrate Panels/Breadcrumb, Panels/BreadcrumbDecorator, Panels/Panel, ThemeDecorator and VirtualList unit tests to Testing Library

---

BodyText/tests/BodyText-specs.js
Button/tests/Button-specs.js
Header/tests/Header-specs.js
Heading/tests/Heading-specs.js

Migrated unit tests from Enzyme to Testing Library for BodyText, Button, Header and Heading components.
WRN-4401

WRN-4401: Migrate BodyText, Button, Header and Heading unit tests to Testing Library

---

ImageItem/tests/ImageItem-specs.js
Item/tests/Item-specs.js
TabGroup/tests/TabGroup-specs.js
ThumbnailItem/tests/ThumbnailItem-specs.js

Migrated unit tests from Enzyme to Testing Library for ImageItem, Item, TabGroup and ThumbnailItem components.
WRN-4403

WRN-4403: Migrate ImageItem, Item, TabGroup and ThumbnailItem unit tests to Testing Library

---

DatePicker/tests/DatePicker-specs.js
DateTimePicker/tests/DateTimePicker-specs.js
Picker/tests/Picker-specs.js
RangePicker/tests/RangePicker-specs.js
TimePicker/tests/TimePicker-specs.js
internal/Picker/tests/Picker-specs.js

Migrated tests from Enzyme to Testing Library.
Changed test structure to work with Testing Library.
WRN-4399

WRN-4399: Migrate DatePicker, DateTimePicker, internal/Picker, Picker, RangePicker, TimePicker unit tests to Testing Library.

---

Checkbox/tests/Checkbox-specs.js
CheckboxItem/tests/CheckboxItem-specs.js
RadioItem/tests/RadioItem-specs.js
Switch/tests/Switch-specs.js
SwitchItem/tests/SwitchItem-specs.js

Migrated tests from Enzyme to Testing Library.
Changed test structure to work with Testing Library.
WRN-4396

WRN-4396: Migrate Checkbox, CheckboxItem, RadioItem, Switch, SwitchItem unit tests to Testing Library.

---

Input/tests/Input-specs.js
Keypad/tests/Keypad-specs.js

Migrated unit tests from Enzyme to Testing Library for Input and Keypad components.
WRN-4404

WRN-4404: Migrate Input and Keypad unit tests to Testing Library

---

MediaPlayer/tests/MediaPlayer-specs.js
SliderButton/tests/SliderButton-specs.js
Spinner/tests/Spinner-specs.js

Migrated unit tests from Enzyme to Testing Library for MediaPlayer, SliderButton and Spinner components.
WRN-4405

WRN-4405: Migrate MediaPlayer, SliderButton and Spinner unit tests to Testing Library

---

IncrementSlider/tests/IncrementSlider-specs.js
Slider/tests/Slider-specs.js

Migrated unit tests from Enzyme to Testing Library for IncrementSlider and Slider components.
WRN-4409

WRN-4409: Migrate IncrementSlider and Slider unit tests to Testing Library

---

Popup/tests/Popup-specs.js
PopupMenu/tests/PopupMenu-specs.js
ProgressBar/tests/ProgressBar-specs.js
ToggleButton/tests/ToggleButton-specs.js
TooltipDecorator/tests/TooltipDecorator-specs.js

Migrated `Popup`, `PopupMenu`, `ProgressBar`, `ToggleButton` and `TooltipDecorator` unit tests to react-testing-library
WRN-4408

WRN-4408: [Agate] Migrate Popup, PopupMenu, ProgressBar, ToggleButton and TooltipDecorator unit tests to Testing Library

---

SliderButton/SliderButtonBehaviorDecorator.js
samples/sampler/stories/default/PopupMenu.js

After CLI updates to 4.1.7, lint warning shows.
Fixed lint warnings
WRN-13647

WRN-13647: Fix lint warnings

---

tests/ui/specs/ToggleButton/ToggleButton-Page.js

WRN-16907: UI Tests Migration - Panel to WindDirectionControl 

---

ImageItem/tests/ImageItem-specs.js
samples/qa-a11y/src/views/VirtualGridList.js
samples/sampler/stories/default/ImageItem.js
samples/sampler/stories/default/VirtualGridList.js
samples/sampler/stories/qa/ImageItem.js
tests/ui/apps/ImageItem/ImageItem-View.js
tests/ui/apps/VirtualList/VirtualGridList/VirtualGridList-View.js

Changed image service.
WRN-17786

WRN-17786: Changed Placehold.it Image service

---

package.json
samples/qa-a11y/package.json
samples/sampler/package.json

Updated to latest dependencies
WRO-2574

WRO-2574: Update Agate to React 18

---

samples/qa-a11y/src/App/App.js
samples/qa-a11y/src/views/ReadAlert.js
samples/sampler/package.json
samples/sampler/stories/qa/Dropdown.js
samples/sampler/stories/qa/Panels.js

Converted class components into functional components in agate samples
WRO-3172

WRO-3172: Updated agate samples with new React style APIs

---

Input/tests/Input-specs.js
Panels/tests/BreadcrumbDecorator-specs.js

Enact-DCO-1.0-Signed-off-by: Alexandru Morariu alexandru.morariu@lgepartner.com
Repaired lint errors.
WRO-4059

WRO-4059: Fix lint warnings from updated lint rules.

---

ColorPicker/ColorPicker.js
Panels/Viewport.js
Slider/SliderBehaviorDecorator.js
SliderButton/SliderButtonBehaviorDecorator.js

Replaced `findDOMNode` with ref
WRO-6457

WRO-6457; Deprecate the dependency with `findDOMNode`

---

tests/ui/apps/VirtualList/VirtualGridList/VirtualGridListScrollTo-View.js
tests/ui/specs/Drawer/Drawer-specs.js
tests/ui/specs/Drawer/DrawerPage.js
tests/ui/specs/Popup/Popup-specs.js
tests/ui/specs/Popup/PopupPage.js
tests/ui/specs/PopupMenu/PopupMenuPage.js
tests/ui/specs/Scroller/Scroller-nativeScroll-specs.js
tests/ui/specs/Scroller/Scroller-translateScroll-specs.js
tests/ui/specs/Slider/Sliders-specs.js

Enact-DCO-1.0-Signed-off-by: Dongsu Won (dongsu.won@lgepartner.com)
- Need to change scrollTo() api to work after setState.
- Need to add delay for drawer ui-test.
- Change scrollTo() api to work after setState.
- Add delay for drawer ui-test.
[//]:# (Related issues, references)
WRO-6250

WRO-6250: Fix ui test fail on jenkins(VirtualGridList, Drawer)

---

samples/qa-a11y/src/index.js

Update sample's index.js with the new selective hydrateRoot pattern.
WRO-7313

WRO-7313: Update sample's index.js with the new selective hydrateRoot pattern.

---

CHANGELOG.md
Dropdown/Dropdown.module.less
styles/colors-base.less
styles/colors-carbon.less
styles/colors-cobalt-day.less
styles/colors-cobalt.less

Dropdown list is not visible on Carbon, Cobalt, Copper, Titanium skins.
Changed dropdown's list item color in order to be visible
WRO-10541

WRO-10541: Dropdown - Cobalt, Copper, Titanium skins - options not showing

---

package.json
samples/qa-a11y/package.json
samples/sampler/package.json

isomorphic test fail due to ilib 14.15.0 released on Sep 2nd
Temporarily fixed ilib version to 14.14.0
WRO-11786
Enact-DCO-1.0-Signed-off-by: SJ RO ([sj.ro@lge.com](mailto:sj.ro@lge.com))

WRO-11786: Fix isomorphic test for agate

---

samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js
samples/sampler/stories/default/Panel.js

Fixed console warnings for Agate Panel by modifying storybook's ThemeEnvironment and Panel.
The spotlightId and hideChildren warnings are fixed.
Further investigation on how the changes made in storybook's ThemeEnvironment and Panel may affect the components.
WRO-13689

WRO-13689: Panel - fix console warnings

---

.travis.yml

Apply codecov
Add the option for coverage check and upload it
WRP-3408

WRP-3408: Apply codecov

---

Button/tests/Button-specs.js
ColorPicker/tests/ColorPicker-specs.js
ContextualPopupDecorator/tests/ContextualPopupDecorator-specs.js
Popup/tests/Popup-specs.js

Increased code coverage for Button, ColorPicker and ContextualPopupDecorator.
WRP-3060

WRP-3060: Increase code coverage for Button, ColorPicker, ContextualPopupDecorator

---

Image/tests/Image-specs.js
Input/tests/Input-specs.js
Keypad/tests/Keypad-specs.js
TabGroup/tests/TabGroup-specs.js

Increased code coverage for Image, Input, Keypad and Tabgroup
WRP-3063

WRP-3063: Increased code coverage for Image, Input, Keypad and Tabgroup

---

DatePicker/tests/DatePicker-specs.js
Dropdown/tests/Dropdown-specs.js
TimePicker/tests/TimePicker-specs.js
internal/DateTime/tests/DateTimeDecorator-specs.js
internal/Picker/tests/Picker-specs.js

Increased code coverage for Dropdown and Picker related modules
WRP-3062

WRP-3062: Increased code coverage for Dropdown and Picker related modules

---

.travis.yml
internal/DateTime/tests/DateTimeDecorator-specs.js

Enact-DCO-1.0-Signed-off-by: Alexandru Morariu alexandru.morariu@lgepartner.com
Removed unused property from unit test.
WRP-6651

WRP-6651: Fixed lint warnings in agate.

---

samples/sampler/package.json

Enact-DCO-1.0-Signed-off-by: Adrian Cocoara [adrian.cocoara@lgepartner.com](mailto:adrian.cocoara@lgepartner.com)
Running enact  bootstrap or npm run serve in samples/sampler with node18 fails.
Added `react-dom: ^18.2.0` as a dependency in samples/sampler.
The root cause comes from "react-element-to-jsx-string" version 14.3.4 module required by @storybook/react in @enact/storybook-utils.
```
"node_modules/@enact/storybook-utils/node_modules/react-element-to-jsx-string": {
"version": "14.3.4",
"resolved": "https://registry.npmjs.org/react-element-to-jsx-string/-/react-element-to-jsx-string-14.3.4.tgz", …
```

WRP-8571: Fixed errors with enact bootstrap on node 18

---

samples/perf-scroller-native/src/App.js
samples/perf-virtualgridlist-native/src/App.js
samples/perf-virtuallist-native-with-different-item-size/src/views/HorizontalDifferentWidthItemList.js
samples/perf-virtuallist-native-with-different-item-size/src/views/VerticalDifferentHeightItemList.js
samples/perf-virtuallist-native-with-different-item-size/src/views/VerticalExpandableDifferentHeightItemList.js
samples/perf-virtuallist-native/src/App.js
samples/qa-virtualgridlistnative-preserve-focus/src/components/SampleVirtualGridList.js

'scrollMode' had the incorrect value on native samples.
Added 'scrollMode' native to all native samples.
WRP-8543

WRP-8543: Fixed 'scrollMode' on native samples

---

.travis.yml

There was an error in the current node version, so it was temporarily fixed to 19.
However, since the error has disappeared since cli 6.0, the current node test is needed again.
Add the current node test.
WRP-16809

WRP-16809: Update .travis.yml to add current node test

---

CHANGELOG.md
package.json
samples/sampler/package.json

Agate repo and sampler have node modules that need major updates.
For Agate root:
Updated `immer` dependency to v10.
There were no breaking changes affecting our code https://github.com/immerjs/immer/releases.
For Agate sampler:
Updated `babel-loader` dependency to v9.
There were no breaking changes affecting our code https://github.com/babel/babel-loader/releases.
For Agate I have also updated minor versions of `enact/docs-utils` and `enact/ui-test-utils`.
For …

WRP-19326: Updated node modules' major versions

---

package.json

Downgraded immer dependency because of conflicting breaking changes with redux-toolkit
Downgraded immer dependency because of conflicting breaking changes with redux-toolkit
ENACT-155

ENACT-155: Downgraded immer dependency to version 9

---

Dropdown/Dropdown.module.less
samples/sampler/.storybook/preview.js

Enact-DCO-1.0-Signed-off-by: Jiye Kim (jiye.kim@lge.com)
Spotlight is truncated in a certain skin of Agate Dropdown.
I added border-radius property to above dropdown container.
WRQ-2632
Enact-DCO-1.0-Signed-off-by: Jiye Kim ([jiye.kim@lge.com](mailto:jiye.kim@lge.com))

WRQ-2632: [Agate] Dropdown: Spotlight is truncated.

---

.github/PULL_REQUEST_TEMPLATE.md

Simplify Pull Request template

---

package.json

Enact-DCO-1.0-Signed-off-by: Juwon Jeong (juwon.jeong@lge.com)
To fix the validate-docs error while Travis test, Update @enact/docs-utils version to 0.4.8.
Update @enact/docs-utils version to 0.4.8

Update @enact/docs-utils version to ^0.4.8 in package.json file

---

ArcPicker/ArcPickerBehaviorDecorator.js
Slider/SliderBehaviorDecorator.js
SliderButton/SliderButtonBehaviorDecorator.js
useScroll/useScroll.js

As [core/platform's API is updated](https://github.com/enactjs/enact/pull/3208/), internal codes need to be updated.
Updated affected API calls.
No changelog as only internal calls are updated.
WRQ-188
[enactjs/enact PR #3208](https://github.com/enactjs/enact/pull/3208/)

WRQ-188: Update internal calls to the updated core/platform APIs

---

Image/tests/Image-specs.js
ImageItem/tests/ImageItem-specs.js
samples/qa-virtualgridlist/src/utils/index.js
samples/qa-virtualgridlistnative-preserve-focus/src/components/SampleVirtualGridList.js
samples/sampler/stories/default/ImageItem.js
tests/ui/apps/ImageItem/ImageItem-View.js
tests/ui/apps/VirtualList/VirtualGridList/VirtualGridList-View.js

Fixed image placeholder URLs
Fixed image placeholder URLs
WRQ-12609
Enact-DCO-1.0-Signed-off-by: Paul Beldean paul.beldean@lgepartner.com

Fixed image placeholder URLs

---

tests/ui/specs/VirtualList/VirtualList/VirtualList-specs.js

Fix nightly ui-test on VirtualList
A page delay was added to a test case to wait for Scroller to finish `scrollTop`
fixed one typo
WRQ-13555

WRQ-13555: [Nightly] [Agate] Fix ui-test on VirtualList

---

.travis.yml
samples/sampler/stories/default/VirtualGridList.js

Scrolltrack does not display on virtualgridlist story by default
Fixed args names for horizontal and vertical scrollbars
WRQ-29957
Enact-DCO-1.0-Signed-off-by: Daniel Stoian (daniel.stoian@lgepartner.com)

WRQ-29957: Fixed VirtualGridList story to load default values

---

package.json

There were high vulnerabilities in enact/agate`s dependencies.
Update minor version dependencies.
Applied npm feature: "overrides": https://github.com/npm/cli/releases/tag/v8.3.0.
This feature can update the 3rd party modules' submodule version.
"overrides": {
"autolinker": "^4.0.0"
}
WRQ- 30239

WRQ- 30239: Fixed high vulnerabilities in Agate

---

package.json
samples/event-logger/package.json
samples/qa-virtualgridlist/package.json
samples/qa-virtualgridlistnative-preserve-focus/package.json
samples/qa-virtuallist/package.json
samples/sampler/npm-shrinkwrap.json
samples/sampler/package.json

Updated package dependencies to fix security vulnerabilities
WRR-1137
Enact-DCO-1.0-Signed-off-by: Ion Andrusciac ion.andrusciac@lgepartner.com

WRR-1137: Updated package dependencies to fix security vulnerabilities

---

tests/ui/specs/RangePicker/RangePicker-specs.js

Fixed ui-test on RangePicker
Added `browser.pause` when the value in the RangePicker is incremented 
WRR-5726
Enact-DCO-1.0-Signed-off-by: Ion Andrusciac ion.andrusciac@lgepartner.com

WRR-5726: Fixed ui-test on `RangePicker`

---

DatePicker/DatePicker.js
Panels/Arrangers.js
Panels/Breadcrumbs.js
Scroller/useThemeScroller.js
TimePicker/TimePicker.js
TooltipDecorator/util.js
internal/$L/$L.js
internal/DateTime/DateTimeDecorator.js

Fixed JSDocs for agate repo.
WRR-10798

WRR-10798: Fixed JSDocs for agate repo

---

DropManager/DropManager.js
Panels/SharedStateDecorator.js
Scroller/Scroller.js
ThemeDecorator/ThemeDecorator.js
VirtualList/VirtualList.js
useScroll/useScroll.js
useScroll/useSpotlight.js

I replaced Context.Provider with Context for our enact components and replaced useContext with use.
WRR-15901

WRR-15901: Replace Context.Provider to Context

---

DropManager/DropManager.js
Panels/SharedStateDecorator.js
Scroller/Scroller.js
ThemeDecorator/ThemeDecorator.js
VirtualList/VirtualList.js
useScroll/useScroll.js
useScroll/useSpotlight.js

I replaced Context.Provider with Context for our limestone components  and replaced useContext with use.
WRR-15901
Enact-DCO-1.0-Signed-off-by: Daniel Stoian (daniel.stoian@lgepartner.com)

WRR-15901: Updated Context for React19

---

tests/ui/specs/DatePicker/DatePicker-specs.js
tests/ui/specs/DateTimePicker/DateTimePicker-specs.js
tests/ui/specs/TimePicker/TimePicker-specs.js

Fixed failed `ui-tests` on Jenkins
WRR-28062
Reviewed-by: Ion Andrusciac (ion.andrusciac@lgepartner.com)

WRR-28062: Fixed failed `ui-tests` on Jenkins
