Popup/Popup.js
Skinnable/Skinnable.js

I added a config option to `ui/Skinnable` to allow it to pass the skin down to its Wrapped component rather than using `SkinContext` which is more complicated.
This PR adopts that prop for `agate/Popup`

Adopt Skinnable prop

---

ToggleButton/ToggleButton.js
ToggleButton/ToggleButton.less
styles/variables-carbon.less
styles/variables-titanium.less

Replace `toggleIndicator` with `underline`
https://github.com/enactjs/agate/issues/25
Sampler: https://github.com/enactjs/agate-apps/pull/36

ToggleButton: underline update

---

Picker/Picker.js
Picker/Picker.less

Fixes #49 
> When trying to use Picker with outside services it didn't update easily. Now we adjusted it to be able to getDerivedStateFromProps. This allows us to still use the Picker logic and allow outside apps to handle it easily. This works fine so far, but there could be some better ways to implement this logic.
>
> We may want to come up with a breakdown between PickerBase and Picker that we see in Moonstone. Maybe what we have now is a good middle ground, but I'm sure other components with trickier states may run into similar problems so we should come up with a more standard solution.
* Refactor into a kind and use `ui/Changeable` to manage the state
* Change "value" prop from `index` to `value` for better intra-framework consistency
I removed the manual spotlight handling and …

Refactor agate/Picker

---

Button/Button.less
LabeledIconButton/LabeledIconButton.js
LabeledIconButton/LabeledIconButton.less

`onClick` handlers attached to `<LabeledIconButton>` do not fire when 5-way selected
* Move Spottable up to the root so it can correctly emulate `onClick` for Enter
* Also move the `agate/Button.ButtonDecorator` to the top so Touchable events can be attached
* Broaden the styling rules for `agate/Button` to show its focus rules when spotted or when within a spotted node.
Will need to fix up the Button ruleset when we land an improve mixin in `@enact/spotlight`
Fixes enactjs/agate-apps#30
Supercedes #52 and enactjs/agate-apps#37

Fix 5-way selection support for LabeledIconButton

---

DropManager/DropManager.js
DropManager/DropManager.less
DropManager/package.json
Rearrangeable/Rearrangeable.js
Rearrangeable/package.json

These two components enable dragging and dropping of rearrangeable interfaces.
Below is an example of the usage:
```
const allSlotNames = ['bottom', 'children', 'top', 'left', 'right'];
const CustomLayout = DropManager(
// Don't provide the "children" slot to Slottable
Slottable({slots: allSlotNames.filter(slot => slot !== 'children')},
Rearrangeable({slots: allSlotNames},
CustomLayoutBase
)
)
);
```
Here, `DropManager` facilitates the movement of the slots and informs `Rearrangeable` of the new structure. `Rearrangeable` takes the slot prop values from `Slottable` and remaps them to their new destinations (provided by `DropManager`, via the `arrangement` prop) and supplies those to the wrapped component (`CustomLayout` in this case), which needs no special knowledge of dragging or being …

Added drag and drop rearrangeable support with 2 new hocs

---

FullscreenPopup/FullscreenPopup.js
FullscreenPopup/FullscreenPopup.less
FullscreenPopup/package.json
Popup/Popup.js
Popup/PopupState.js
styles/colors-carbon.less
styles/colors-electro.less
styles/colors-titanium.less
styles/variables-carbon.less
styles/variables-electro.less
styles/variables-titanium.less

Adding the `FullscreenPopup` component.
Usage:
```
<FullscreenPopup
onClose={this.handleClose}
open={open}
>
This is an example of a fullscreen popup.
</FullscreenPopup>
```
So far details are light-to-nonexistent regarding how the popup should be styled. It should ultimately respect theme styling (colors/padding). We can start a discussion to grow the needed styling rules and apply them in this PR.
Additional Considerations:
I've changed the `PopupState` component (used in `Popup`) into a `hoc` and moved into its own module, since it could/should also be used with `FullscreenPopup`. There are shared behaviors within popups in general that would be best served with centralized management.

PLAT-68524: Add FullScreenPopup component

---

ColorPicker/ColorPicker.js

`ColorPicker` needs a value to set the HSL values for the sliders in order to fix this error when there is no default value:

ColorPicker: Set default value

---

GridListImageItem/GridListImageItem.js
GridListImageItem/GridListImageItem.less
GridListImageItem/package.json
styles/variables-carbon.less
styles/variables-electro.less
styles/variables-titanium.less

Extends `ui/GridListImageItem` with agate-styled `Icon` component. We don't have any agate-specific requirements for `Image` yet so `ui/Image` is used for now.
In order to support both the Album art and video thumbnail requirement, I added an `aspectRatio` prop which sizes the height of the image relative to the width. The sizing using a CSS variable, `--agate-aspect-ratio` along with a `padding` and `calc()` to size the image node.
```
<GridListImageItem aspectRatio="16:9" ... />
```
It's possible to add space around the image using `margin` instead of `padding` and maintain the same aspect ratio but I thought i more likely we'd want to keep the thumbnail close to the caption so I've used `padding`. The `margin` core remains commented out for future consideration.

PLAT-69809: Add GridListImageItem component

---

Panels/TabbedPanels.js
Panels/TabbedPanels.less

TabbedPanels Tabs get all smushed together on Chrome 53, rather than being properly spaced (as expected). This was due to the fact that Cell was being assigned Layout rules when the inner component should have just been a child, rather than leveraging the `component` prop of `Cell`.
Generally, `Cell` and `Layout` should not be the same DOM node since early support for flex-box *does NOT* handle this case well. Newer browsers don't appear to exhibit this quirky behavior, but the older ones do. `<table>` and `<td>` cannot be the same DOM node; `<frame>` and `<frameset>` cannot either; `Layout` and `Cell` have a similar relationship.

PLAT-70504: Fixed TabbedPanels Tabs layout being squished together

---

Panels/Panels.js
Panels/TabbedPanels.js

Moving in some tricks we used for moonstone. Adding data-index, to prevent re-renders. Also adding in `hideChildren` to fade in. This will make the transitions quicker.

Added some panel optimization

---

DropManager/DropManager.js

If `arrangement` prop is updated by the parent, `DropManager` fails to respect the value. It only needs to use the arrangement state while it's in an arrangeable state.
Enact-DCO-1.0-Signed-off-by: Stephen Choi <stephen.choi@lge.com>

PLAT-70638: Fix DropManager to only apply updated arrangements while arranging

---

TabGroup/TabGroup.js

Reverts enactjs/agate#90
I need to do more validation testing. `selected` in this component is a boolean, rather than an index number.

Revert "PLAT-71670: Set selected state to Group"

---

Switch/Switch.js
Switch/Switch.less
SwitchItem/SwitchItem.js
SwitchItem/SwitchItem.less

Converted custom layout to Layout component for better reliability, ignore taps on the Switch when inside SwitchItem, convert onTaps to onClicks to avoid quirk in Tappable, general cleanup.

PLAT-71634: Cleanup SwitchItem and Switch

---

AgateDecorator/AgateDecorator.less
styles/colors-carbon.less
styles/colors-copper-day.less
styles/colors-copper.less
styles/colors-electro.less
styles/colors-titanium.less

In old Chrome 53, it didn't know how to render a background image URL + a CSS-variable-based HSLA color value in a radial-gradient on one DOM node and would just show 2 of the 3 backgrounds being applied. This moves the URL to a separate variable and applies that to a new background layer (pseudo-class).
Bonus, now the URL background can be used in other places too.
This bug only appears in the one place that matters (in the build). For true integration diligence, you'll need to test this on our build, however, I can verify it does work.

Background image didn't show on Chrome 53

---

DropManager/DropManager.js

When `arrangement` state is managed by the parent component, then there's no need for the `DropManager` component to manage the state on its own. This rather causes a problem as these values can get out of sync.
Enact-DCO-1.0-Signed-off-by: Stephen Choi <stephen.choi@lge.com>

PLAT-72043: Remove arrangement state from DropManager

---

AgateDecorator/AgateDecorator.less
Button/Button.less
Divider/Divider.less
styles/variables-carbon.less
styles/variables-copper.less
styles/variables-electro.less
styles/variables-titanium.less

https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures
Copper uses a wide letter spacing which is incompatible with ligatures. This assigns and associates the ligatures settings with the skin.
This is effect visible in words like "coffee" and "left" on the welcome screen and map destinations.

Fixed ligatures usage highlighted by the new wider letter-spacing

---

styles/skin.less

Skins should now be able to ignore newly created variables for components
This change, looking seemly simple, allows components to specify one initial set of colors/variables in one pair of files, allowing the others to simply ignore or override those variables, without breaking the whole system due to a variable missing or not being defined.
This can be viewed as a first step, albeit the most important step. Future steps to refine this could include:
* removing repetitive or already defined variables/values in each of the skin files which don't differ from the established base skin.
* establishing a true "base" skin which has extremely generic colors and variables, rather than one that's a little opinionated

PLAT-80257: Durable Skins

---

Button/Button.js
IconButton/IconButton.js
LabeledIcon/LabeledIcon.js
LabeledIconButton/LabeledIconButton.js
Picker/Picker.js
ProgressBar/ProgressBar.js
SliderButton/SliderButton.js
ToggleButton/ToggleButton.js

Update `publicClassNames` for `LabeledIcon`, `LabeledIconButton`, `Picker`, `ProgressBar`, `SliderButton`, and `ToggleButton`.

PLAT-80254: Update Agate components to expose public class names

---

IncrementSlider/IncrementSlider.js
Popup/Popup.js
Popup/PopupState.js
Slider/SliderBehaviorDecorator.js

This fixes the react life-cycle deprecation warnings in the following components:
- `PopupState`
- `SliderBehaviorDecorator`
I have also fixed a couple of associated errors which made testing this lifecycle change difficult or impossible.

PLAT-84598: Fix react lifecycle  deprecation warnings

---

data/ProviderDecorator/ProviderDecorator.js

We had some code that was directly mutating state to cache service requests. We've discussed other ways to handle that particular concern but this PR freezes the state object in dev-mode to prevent that mutation.

PLAT-85937: Freeze state in dev mode to prevent direct mutation

---

Panels/TabbedPanels.js

There is no way to remove the close button of a TabbedPanels from app.
When this PR is merged, we can use `noCloseButton` prop to hide the close button on the TabbedPanels.
Enact-DCO-1.0-Signed-off-by: Baekwoo Jung (baekwoo.jung@lge.com)

ENYO-6275: Fixed `noCloseButton` prop to pass TabbedPanels to panels

---

Icon/Icon.module.less
styles/variables-gallium.less
styles/variables.less

The Icon position in only `Copper` and `Cobalt` skins shifted to the right in Icon Button.
The Icon `letter-spacing` and `text-index` styles were inherited from Button with `normal` value.
But the those styles of Button in the `Copper` and `Cobalt` skins were updated with `9x` in https://github.com/enactjs/agate/pull/97 and https://github.com/enactjs/agate/pull/101.
So we needed to define those styles in Icon separately.
Browser did not recognize `normal` value for them. So I defined those styles in Icon as `initial` to override the those styles in Button.
ENYO-6273

ENYO-6273: Define letter-spacing and text-index in Icon instead of being inherited from Button

---

Scrollable/Scrollable.js

The `Scroller` component disables its container when a wheel event starts, but does not enable the container again after the scroll stops.
We explicitly enable the `Scroller` after a `scrollStop` event, we just need to also check if the scroll was caused by a wheel event.

PLAT-86435: Enable Scroller container after wheeling

---

Item/Item.js

Conditionally apply shrink prop based on the presence of label.
The item field will now display, even if empty-string to preserve layout, in case that's your intent. Undefined or null will remove it entirely (for the case of you having not set it).

PLAT-86438: Conditionally apply shrink prop based on the presence of label

---

Popup/Popup.js
Popup/PopupState.js
PopupMenu/PopupMenu.js

We want to make sure that `onClose` is called when the popup is closed via the close button.

PLAT-86660: agate/Popup should forward to `onClose` when the close button is tapped/clicked

---

Input/pointer.js

Advances in our touch event handling for `moonstone` have left `agate` behind.  This patch ensures consistent handling of touch and pointer events for `agate/Input`.

PLAT-87047: Connect Button on the wifi password window is not able to be tapped but must be clicked with mouse device

---

SwitchItem/SwitchItem.js

Tapping a SwitchItem when disable will still emit the `onToggle` event
`onToggle` is mapped to `onClick` by `Toggleable` so adding a handler that suppresses forwarding `onClick` when disabled resolves the issue.

PLAT-86999: Suppress onToggle when disabled

---

AgateDecorator/AgateDecorator.js

In PLAT-86868, to support language changing, the root AgateDecorator needs to support I18nDecorator.
Added an implementation for optional I18nDecorator usage, like in the [generic ThemeDecorator template](https://github.com/enactjs/templates/blob/master/packages/theme/template/ThemeDecorator/ThemeDecorator.js#L65)

Add I18nDecorator to AgateDecorator for in-app iLib support

---

data/ProviderDecorator/ProviderDecorator.js
package.json

Prior implementations (#134, #135) were naive and should have used `hasOwnProperty()`. Instead of adding that, added the small `deep-freeze` module which handles this correctly.

PLAT-85937: Add deep-freeze in dev mode

---

styles/colors-gallium-day.less
styles/colors-gallium-night.less
styles/variables-base.less
styles/variables-gallium.less

Updated `Slider` colors and knob position.
When focused, knob grows from 35px to 45px in height, and 5px over the edge of the progressbar:
Normal knob at the edge of the progressbar:

PLAT-95484: Update Slider

---

Panels/Panels.js
Panels/Panels.module.less
styles/colors-base.less
styles/colors-carbon.less
styles/colors-cobalt-day.less
styles/colors-copper-day.less
styles/colors-copper.less
styles/colors-electro.less
styles/colors-gallium-night.less
styles/colors-titanium.less
styles/variables-base.less
styles/variables-carbon.less
styles/variables-gallium.less

Added a `cover` prop to Panels which is now responsible for determining several states of screen coverage, definable by a skin. Initially supported states are "full" and "partial". "full" is expected to fully cover the screen, in any skin (at the moment), while "partial" covers some proportion of the screen, defined by the preferred layout of the skin.
This also includes the ability for a skin to choose a different background color/image for a partial panels instance that differs from a full-screen scenario, since one may need to be a basic translucency while others may want an opaque occluding background. Skins are updated to include an appropriate background and size for this feature.
Other possible `cover` values in the future could be values like "pip", "floater", "partial-reversed", …

PLAT-98292: Adds skin-based partial-coverage Panels customization

---

AgateDecorator/AgateDecorator.js
AgateDecorator/tests/AgateDecorator-specs.js
Skinnable/Skinnable.js
styles/skin.less

Converted existing skins to use `skinVariants` to capture day vs night mode. All skins can be easily switched between and their appropriate day or night skin will switch along with the main one.
A companion branch of the same name is available in the https://github.com/enyojs/webos-auto-settings repo.

PLAT-97799: Add Skin Variants for night mode

---

SliderButton/SliderButton.js
SliderButton/SliderButton.module.less
styles/colors-base.less
styles/colors-gallium-day.less
styles/colors-gallium-night.less
styles/variables-base.less
styles/variables-gallium.less

SliderButton was largely ignored after its initial creation. This PR aims to improve its customizability by a skin, and leverages that customizability to make the SliderButton component, when used in the Gallium skin, look like it matches the target visual style.

ENYO-6393: Fix up SliderButton

---

IncrementSlider/IncrementSlider.module.less
Slider/Slider.module.less
styles/variables-base.less
styles/variables-electro.less
styles/variables-gallium.less

The Gallium slider design shows the knob always fully within the bounds of the slider track. This update extends the visible track to protrude past the measurement boundaries of the slider track, so the knob never appears to leave the track area.
This is achieved by relocating and decoupling the visuals from the "math container" of the slider. The benefit of which is that now the knob always remains centered under the drag point, and behaves as expected when the extreme edges are clicked, as well as remains stationary on repeated tapping on the bar.
One minor visual regression arose with the Electro skin, which is also corrected in this PR. Conveniently, this made the Electro configuration simpler while creating no visual differences. All other skins were unaffected by this change.
The …

PLAT-98491: Gallium slider knob fully encapsulated

---

Button/Button.js

Reverts the changes from #181 to restore compatibility with Enact 3.2.5. It does maintain deleting the `spriteCount` prop to avoid possible prop type warnings.
The changes will be reapplied after releasing alpha.11.

ENYO-6364: Restore compatibility with Enact 3.2.5

---

samples/sampler/src/AgateEnvironment/AgateEnvironment.js

- Add locale to the Agate Storybook Global Knobs
PLAT-99809
Enact-DCO-1.0-Signed-off-by: Seungho Park <seunghoh.park@lge.com>

PLAT-99809: Add locale to the Global Knobs of sampler

---

.travis.yml

Adds setup steps to clone `develop` of Enact, bootstrap Enact, and use it linked into sandstone.

PLAT-100154: Link develop Enact in theme library Travis

---

Panels/TabbedPanels.js
samples/sampler/src/AgateEnvironment/AgateEnvironment.js

There is no way to pass some props to Panels via TabbedPanels.
When this PR is merged, App can pass props such as duration, noAnimation, and etc to panels.
(Added props: arranger, childProps, closeButtonAriaLabel, duration, noAnimation, onApplicationClose, onBack)
Enact-DCO-1.0-Signed-off-by: Baekwoo Jung (baekwoo.jung@lge.com)

PLAT-98821: Changed the `TabbedPanels` components structure to pass props to panels

---

Scrollable/ScrollButtons.js
Scrollable/ScrollThumb.js
Scrollable/Scrollable.js
Scrollable/Scrollbar.js
Scrollable/useEvent.js
Scrollable/useScrollbar.js
Scrollable/useSpotlight.js
Scroller/Scroller.js
Scroller/useEvent.js
VirtualList/VirtualList.js
VirtualList/VirtualListBasic.js
VirtualList/useEvent.js
VirtualList/usePreventScroll.js
VirtualList/useSpotlight.js
samples/sampler/stories/default/VirtualList.js

All modules from ui/Scrollable were moved to ui/useScroll.
VirtualListBase from ui/VirtualList.js was replaced with VirtualListBasic
ScrollerBase from ui/Scroller.js was replaced with ScrollerBasic
So some modules should be imported from proper modules.
Import
- not ui/Scrollable but ui/useScroll
- not VirtualBase but VirtualListBasic from ui/VirtualList
- not ScrollerBase but ScrollerBasic from ui/Scroller
PLAT-101126 …

PLAT-101126: Replace VirtualListBase, ScrollerBase, and Scrollable with VirtualListBasic, ScrollerBasic, and useScroll

---

Scroller/Scroller.js
Scroller/ScrollerBasic.js
VirtualList/VirtualList.js

Fix VirtualList and Scroller JSDoc parse error
```
Invalid reference: agate/VirtualList.VirtualListBasic:
type: extends - VirtualList in /docs/raw/agate/VirtualList/VirtualList.js:34
type: extends - VirtualGridList in /docs/raw/agate/VirtualList/VirtualList.js:221
```

PLAT-100708: Fix VirtualList and Scroller JSDoc parse error

---

Scroller/useThemeScroller.js
VirtualList/VirtualList.js
VirtualList/useEvent.js
VirtualList/usePreventScroll.js
VirtualList/useSpotlight.js
VirtualList/useThemeVirtualList.js

Modify the scroller and virtuallist variables in sandstone and agate to be the same.
Enact-DCO-1.0-Signed-off-by: Baekwoo Jung (baekwoo.jung@lge.com)

PLAT-101422: Sync naming in VirtualList and Scroller between sandstone and agate

---

Panels/TabbedPanels.js

I fixed the wrong prop types in TabbedPanels that shows an error on the console.

PLAT-100617: Fixed the wrong prop types

---

Scroller/Scroller.js
VirtualList/VirtualList.js
samples/sampler/stories/default/VirtualList.js

* Update samplers based on `VirtualList` and `Scroller` APIs
1) There was some prop changes, and knob bug in current sampler.
* Check updated props in samplers
* Resolve some knob default param problem (Set defaultPops after HOC.)
* Add `scrollMode` knob. 
1) Add `scrollMode` knob in `VirtualList`, `VirtuaiGridList`, and `Scroller` samplers
2) Remove `VirtualList-native` samples and merge into `VirtualList` samples. (native is default.)
[//]: # (Were …

PLAT-101530: Update samplers based on VirtualList and Scroller APIs

---

.travis.yml
Scroller/Scroller.js
Scroller/useThemeScroller.js
VirtualList/VirtualList.js
VirtualList/useThemeVirtualList.js
useScroll/useScroll.js

useScroll, useThemeScroll, useThemeVirtualList, and useThemeScroller referred the instance of scroll content which is ui/VirtualListBasic or ui/ScrollerBasic. That instance is shared by calling setScrollContentHandle in the ui/VirtualListBasic or ui/ScrollerBasic. But ui/VirtualListBasic and ui/ScrollerBasic are React component. So those instance could be referred by ref.
Bind scroll content instance with ref instead of calling the `setScrollContentHandle `.
[//]: # …

PLAT-101226: Scroller Cleanup> Bind scroll content instance with ref

---

Scroller/useThemeScroller.js
VirtualList/usePreventScroll.js
VirtualList/useThemeVirtualList.js
useScroll/useEvent.js
useScroll/useScroll.js

- Extract the `scrollMode` from not `context` parameter but `props` parameter.
- Rename `propsObject` as `rest` and cleanup
PLAT-101226

PLAT-101226: Scroller Cleanup> scrollMode, propsObject, and so on

---

AgateDecorator/AgateDecorator.js

Previously, we supported I18nDecorator without any config options passed. This allowed resulted in async iLib usage.  Prerendering multi-locales currently requires synchronous operation (the initial state prior to async callbacks is locale-less).  This changes AgateDecorator to setup I18nDecorator with `{sync: true}` and allow agate apps to prerender multiple locale builds.

PLAT-102854: Use I18nDecorator in synchronous mode to support prerendering.

---

Button/Button.module.less

`backdrop-filter` was added to `Button` as a technology demonstration and is not necessary for production at this time.

PLAT-101754: Remove the experimental feature `backdrop-filter`

---

samples/sampler/stories/default/VirtualList.js

In some samples, the layout is different depending on the resolution.
[//]: # (What is the impact of this change and *why* was it made?) 
Apply ri.scale properly.
- In most cases, use ri.scaleToRem.
- Use the ri.scale method to pass parameter numerically or to values related to Knobs.
N/A
ENYO-6440

ENYO-6440: Apply ri-scale on sampler and qa-sampler

---

Scroller/Scroller.js
VirtualList/VirtualList.js
VirtualList/useThemeVirtualList.js

There were several code fragments for overscrolling which is not supported in Agate. We don't have any requirement for it, removed unused code.

PLAT-99658: Removed unused code

---

Scroller/useThemeScroller.js

Agate sampler shows console warning of React does not recognize the `scrollAndFocusScrollbarButton` prop on a DOM element
Delete prop on `useThemeScroller` render

ENYO-6444: Fix console warning of scrollAndFocusScrollbarButton prop

---

samples/sampler/package.json

Explicitly sets `"theme": "agate"` to the Sampler `package.json`. This is done both for reference/example and to ensure all current/future agate-specific settings are accessible for storybook.

PLAT-105257: Enact repo package.json cleanup

---

package.json

This patch adds a missing `warning` dependency.

PLAT-105567: Fix agate/VirtualList unit tests

---

.travis.yml
VirtualList/useThemeVirtualList.js

To remove the `div` with role attribute, the `itemRenderer` was renamed as `placeholderRenderer` in https://github.com/enactjs/enact/pull/2770. So all theme libraries should be updated align to that API.
We don't need to handle the `needsScrollingPlaceholder`. In other theme library, it was already deprecated.
PLAT-107424

PLAT-107424: Reduce the number of DOM elements in VirtualList

---

LabeledIcon/LabeledIcon.js
LabeledIconButton/LabeledIconButton.js

Fixed "inline is not a function" error on LabeledIcon and LabeledIconButton.
This error is due to ui/Slottable migration from `kind` to `function`
Changed import from `ui/LabeledIcon` to `ui/LabeldIconBase` as it looks make sense to me rather than removing the use of inline
Enact-DCO-1.0-Signed-off-by: Seungho Park <seunghoh.park@lge.com>

PLAT-107712: Fix `inline` not found error on LabeledIcon and LabeledIconButton

---

PopupMenu/PopupMenu.js
samples/sampler/stories/default/Popup.js
samples/sampler/stories/default/PopupMenu.js

Add `closeButtonLabel` prop so that developer can customize string for `closeButton`
Add `popupMenu` sampler
Enact-DCO-1.0-Signed-off-by: Seungho Park <seunghoh.park@lge.com>

PLAT-106938: Add prop to PopupMenu for customizing closeButton string 

---

useScroll/useScroll.js
useScroll/useScrollbar.js

After migrating hooks, `isUpdatedScrollbarTrack` cannot be referenced because the variable is updated later than `alertScrollbarTrackAfterRendered`.
To show the scrollbar at the initial time, we need to remove the condition.

ENYO-6446: Fix not showing scrollbar at initial time

---

VirtualList/useThemeVirtualList.js
useScroll/useEvent.js
useScroll/useScroll.js
useScroll/useThemeScrollContentHandle.js

This PR fixes jumping focus when keys pressed in a row in VirtualList.
1) directional keys right after Page up/down
2) an opposite directioanl key right after a series of directional keys
The first issue occurs when a user pressed directional key(up/down) right after page up/down key.
The list blurs the current focus and scrolls to the target position by page up/down key and then focuses the item. But if the directional key got in before focusing the item by page up/down key, the spotlight gives the focus the item nearby mouse pointer position(https://github.com/enactjs/enact/pull/1292), and then list focuses the item by page up/down key.
I confirmed that this issue is from moonstone and fixed this by pausing spotlight while page up/down key handling.
The second issue occurs when a user …

PLAT-104180: VirtualList: Fix jumping focus when keys pressed in a row

---

useScroll/useEvent.js
useScroll/useScroll.js

The wheeling status of a scroller is not correctly handled and it affects the behavior of a scroller after a scroller stops.
Since this change does not affect the actual UI/UX until PLAT-113654 is fixed, there is no changelog entry.

Fixed wheeling status to be handled correctly

---

VirtualList/useEvent.js
VirtualList/useSpotlight.js
VirtualList/useThemeVirtualList.js

We're using an internal `getNumberValue` function to convert a string into a number for internal logic. The current implementation of `getNumberLogic` is much faster than `parseInt` but if a string is _undefined_ or _a string contains any character beside space_, it returns 0 instead of invalid value like NaN so we can't catch an exceptional case.
Also, in our usage, `getNumberValue` should return an invalid value like _-1_ or _NaN_ to test if a DOM node is an item or not since we use this function to check `data-index` attribute value of an item's DOM node.
To handle this issue, this PR updates `getNumberValue` with another fast implementation and makes it to return _-1_ for an invalid string.

PLAT-113850: Fixed broken logic covering edge cases of an invalid `data-index` value

---

samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js

Even though changing the `skin`, the `accent` and the `highlight` colors were preserved. So it was hard to verify the updated CSS styles based on the default `accent` and the `highlight` colors in the changed skin.
The `default skin styles` knob is now supported to use default `accent` and `highlight` colors instead of the preserved colors. If checking it, then the `accent` and `highlight` color knobs will be hidden.
Step to reproduce:
1. Select `Agate > Button`
2. Select `Global Knobs`
3. Select `Cobalt` as the `skin`
4. Check `default skin styles`
Expected Result: 
Button background color changes from  #E16253 to white because the highlight color of the Cobalt is white.
Before PR:
After PR:

PLAT-112159: Support `default skin styles` knob to use default accent and highlight colors

---

Input/InputSpotlightDecorator.js

`Input` component covers a whole screen except an input field with a scrim to block any user interaction during input, and there is no option to disable this feature.
This PR adds an option to disable pointer lock to support various UX requirements.
Ref: PLAT-113698, PLAT-87249 (related)

Added `noLockPointer` config to `InputSpotlightDecorator`

---

samples/sampler/package.json

* Fixes in-editor linting of sampler by removing localized eslintConfig overrides.

PLAT-115835: In-editor linting cleanup

---

AgateDecorator/AgateDecorator.js
package.json

* Updates `@enact/ui-test-utils` dependency to `0.5.0`
* Fixes `AgateDecorator`'s import of `ThemeDecorator` to be relative rather than absolute.

PLAT-113569: Update @enact/ui-test-utils to 0.5.0

---

package.json

* Updates peer dependency to support all `-webos*` variants (both old `ilib-webos-tv` and new `ilib-webos` version naming)

PLAT-113142: Use ilib-webos NPM package in webOS templates and framework setup

---

VirtualList/tests/VirtualList-specs.js
useScroll/ScrollButtons.js
useScroll/Scrollbar.js
useScroll/Scrollbar.module.less
useScroll/useScroll.js

There is render prop pattern left in agate/useScroll/ScrollbarButtons.
Remove render prop pattern in agate/ScrollbarButtons
- Convert ScrollButtons React Component to useScroll hook function.
- Fix minor bug about horizontal scroller width. ( horizontal thumb was rendered to very small width.)
PLAT-104513

PLAT-104513: Remove render prop from ScrollbarButtons

---

Panels/TabbedPanels.js
TabGroup/TabGroup.js
samples/sampler/stories/default/TabbedPanels.js

Cannot change tab on Agate TabbedPanels sampler 
- Fix `TabbedPannels` sampler to work.
- Move default props of `TabbedPanels` to be referenced when calling mergeComponentMetadata.
- Fix console error when change skin. Remove the wrong `inline` props to ToggleButton. 
PLAT-116224

PLAT-116224: Fix TabbedPanels Sampler to work

---

Drawer/Drawer.js
Popup/Popup.js
PopupMenu/PopupMenu.js
samples/sampler/stories/default/Drawer.js

[Agate a11y] Support Audio Guidance in Drawer, Popup, PopupMenu
- Add role:alert to `Drawer`, `Popup`, and `PopupMenu`
- Fix prop error when select drawer open and `open cavas in new tab` button on `Drawer` sampler
PLAT-104513

PLAT-115996: Support Audio Guidance in Drawer, Popup, PopupMenu

---

SwitchItem/SwitchItem.js

SwitchItem reads checking status (checked/unchecked) along with a toggled status (on/off) but we just need a toggled status. To fix this, updated aria role from 'checkbox' to 'button'.

PLAT-115993: Updated a11y readout of SwitchItem

---

Dropdown/Dropdown.js

After making a selection from a dropdown menu, focus would be lost and unrecoverable.
Upon closing (hiding) the menu, the focus would remain inside the dropdown list menu popup, and since the list container was set to "self-only", spotlight wasn't allowed to leave that container. However, the container was only hidden, not destroyed, so the normal flow couldn't happen, causing Spotlight to just be stuck in an invisible box, like a real-life mime.
From @germboy:
> I added a `Spotlight.focus()`  bit in the dropdown transition component’s `onHide` method that will set focus back to the dropdown button/item when it closes.
I added several other aria props and ID from Sandstone to help with accessibility.

FORTECH-102: Fixed focus on dropdown activator after selection

---

Dropdown/Dropdown.js
samples/sampler/stories/default/Dropdown.js

[PDM App: Not able to select Dropdown options for the displays at the bottom.
- Adjust Dropdown direction by checking the overflow status.
- If there is a parent node with `overflow` property like `Scroller`, the space is calculated by this node.
- Add qa-sampler for checking the behavior 
PLAT-114355

PLAT-114355: Adjust Dropdown direction to display properly at the bottom

---

ThemeDecorator/ThemeDecorator.module.less
styles/colors-base.less
styles/colors-carbon.less
styles/colors-cobalt-day.less
styles/colors-cobalt.less
styles/colors-copper-day.less
styles/colors-copper.less
styles/colors-electro.less
styles/colors-gallium-day.less
styles/colors-gallium-night.less
styles/colors-silicon-day.less
styles/colors-silicon-night.less
styles/colors-titanium.less

When hovering a disabled Dropdown Button, the text on it disappears
When hovering the focused and disabled components, we restored their natural opacity, then assign the faded text/content color. But it occurred more problems in Agate because there are several text colors. For example, some text colors are white and another text colors are black. So the faded text/content color could be white or black, then one of them can't be seen.
The Dropdown Button color is white and the hovered disabled text color is white because assigning the faded text/content color as I mentioned before.
So I hope we hold the disabled opacity and color.

PLAT-119500: Preserve opacity and color when hovering disabled components

---

Dropdown/Dropdown.js

[Agate a11y]  Checked message cut off in Dropdown
When select a option of dropdown, the a11y message is different depending on the timing.
Expected Result: Provides a consistent A11y.. Read out `Option 2 checked Option 2 Button` or Read out `Option 2 Button` Always
Actual Result: Sometime Read out `Option 2 Button`. And Sometime `Option 2 checked Option 2 Button`
Sandstone is always read out  `Option 2 Button` . 
**So I fix the focus timing to onClose rather than onHide.**
This is also the same as Sandstone's implementation.
[//]: # (How …

PLAT-118160: Fix Checked message cut off in Dropdown

---

MediaPlayer/MediaPlayer.js

This PR adds a11y support to MediaPlayer.
If you move the knob on the slider, it will read "Jump to x minutes x seconds".

PLAT-118165: Add a11y support to MediaPlayer

---

Button/Button.js
samples/sampler/stories/default/Button.js

Button's Icon component cannot get silicon skin
-Refer the latest Icon component in Button to apply the extended icon list.
-Provide silicon icon list in the Button sampler.
PLAT-119661

PLAT-119661: Fix Button's Icon component cannot get silicon skin

---

ThemeDecorator/ThemeDecorator.js

Enact-DCO-1.0-Signed-off-by: Jeongran Jang <jeongran.jang@lge.com>
For FloatingLayerDecorator does not always need to be flowed by `.enact-fit` class.
Add `disableFullscreen` config prop in ThemeDecorator component to disable `.enact-fit` optionally.
PLAT-120786

PLAT-120786: Exclude enact-fit css class optionally

---

styles/colors-silicon-night.less

Fixed bug where slider bar is not visible for IncrementSlider, Slider and ProgressBar when Silicon skin with night mode is applied

FORTECH-113: Fix to make the slider bar visible in IncrementSlider, Slider, and ProgressBar visible properly with night mode

---

ContextualPopupDecorator/ContextualPopupDecorator.js

Enact-DCO-1.0-Signed-off-by: Jeongran Jang <jeongran.jang@lge.com>
ContextualPopupDecorator's popup disappears when RTL is changed
Re-position` ContextualPopup` when change the RTL prop.
PLAT-117980

PLAT-117980: Fix ContextualPopupDecorator's popup disappears when RTL is changed

---

tests/screenshot/apps/AgateComponents.js
tests/screenshot/apps/components/LabeledItem.js
tests/screenshot/apps/importer.js
tests/screenshot/specs/AgateSilicon-specs.js
tests/screenshot/specs/AgateSiliconNight-specs.js

Silicon skin has been included in screenshot tests.
In addition, A `LabeledItem` component screenshot tests has been removed in all skins because it will be deprecated.

PLAT-122750: Include Silicon skin in screenshot tests

---

CHANGELOG.md
LabeledIconButton/LabeledIconButton.module.less

Fixed bug in LabeledIconButton component so that Icon in huge size is not cut off any longer.

PLAT-122792: LabeledIconButton: Huge Icon is cut off.

---

CHANGELOG.md
Panels/Panels.module.less
styles/colors-base.less
styles/colors-carbon.less
styles/colors-electro.less
styles/colors-silicon-day.less
styles/colors-titanium.less

**Checklist**
I have read and understand the contribution guide
A CHANGELOG entry is included
**Issue Resolved / Feature Added**
Agate - Reverted incrementSlider button color for Gallium. It was altered when developing IncrementSlider for Silicon in  #286 and this issue was highlighted in the screenshot tests.
**Links**
PLAT-122734

PLAT-122734: Reverted incrementSlider button color for Gallium

---

CHANGELOG.md
samples/sampler/stories/default/Heading.js
styles/colors-electro.less
styles/variables-base.less
styles/variables-carbon.less
styles/variables-cobalt.less
styles/variables-copper.less
styles/variables-electro.less
styles/variables-gallium.less
styles/variables-silicon.less
styles/variables-titanium.less

Agate - In the Heading story, the 'spacing' prop had no effect for Silicon and Gallium skin. 
Added support for spacing for these 2 skins
PLAT-123186

PLAT-123186: Heading -  Added `spacing`  support for Gallium and Silicon

---

samples/sampler/stories/default/RadioItem.js

Added `onChange` log in sampler Action tab for Agate RadioItem component.

PLAT-122721: RadioItem: No `onChange` log in sampler Action tab

---

samples/sampler/stories/default/TabbedPanels.js

Agate - In the TabbedPanels story, when changing the 'orientation' prop, the icons for the buttons were not changing.
This was solved by conditionally rendering icons based on the 'orientation' value
PLAT-123135

PLAT-123135: TabbedPanels: added arrow direction change of buttons when orientation is changed

---

tests/screenshot/apps/AgateComponents.js
tests/screenshot/apps/components/BodyText.js
tests/screenshot/apps/components/Button.js
tests/screenshot/apps/components/ColorPicker.js
tests/screenshot/apps/components/DatePicker.js
tests/screenshot/apps/components/DateTimePicker.js
tests/screenshot/apps/components/MediaPlayer.js
tests/screenshot/apps/components/Picker.js
tests/screenshot/apps/components/ProgressBar.js
tests/screenshot/apps/components/RangePicker.js
tests/screenshot/apps/components/Slider.js
tests/screenshot/apps/components/SliderButton.js
tests/screenshot/apps/components/TimePicker.js
tests/screenshot/apps/components/ToggleButton.js
tests/screenshot/apps/importer.js

Agate - added more component views for screenshot test (new: BodyText, ColorPicker, DatePicker, MediaPlayer, RangePicker, SliderButton, TimePicker; modified: ToggleButton)
* Root Cause
=> There were only 16 component views for screenshot test in https://github.com/enactjs/agate/tree/develop/tests/screenshot/apps/components. But there are 45 public ui components.
Solution -> Added more component views for screenshot test
PLAT-122911

PLAT-122911: Added more component views for screenshot test - set 3

---

samples/sampler/stories/default/TabbedPanels.js

Depending on the `rtl` prop from `I18nContextDecorator` and the `orientation` prop in TabbedPanels, the next and previous icons shows properly in it.

PLAT-123127: Fix to flip next and previous icons in RTL in TabbedPanels

---

CHANGELOG.md
Heading/Heading.js
PopupMenu/PopupMenu.js
PopupMenu/PopupMenu.module.less
styles/colors-base.less
tests/screenshot/apps/components/PopupMenu.js

Issue: The title in `PopupMenu` is not distinguishable
Solution: Added `publicClassNames` in `Heading` component so I can overwrite the style for color in `PopupMenu` component
PLAT-124529

PLAT-124529: Fixed title in PopupMenu to be distinguishable

---

CHANGELOG.md
Input/InputSpotlightDecorator.js

Invoking `preventDefault` from a destructured value caused a run time error
Remove `preventDefault` from destructuring and call on event object

PLAT-113577: Fix Input to not desctructure preventDefault

---

styles/variables-base.less
styles/variables-carbon.less
styles/variables-electro.less
styles/variables-gallium.less
styles/variables-silicon.less

Issue: Close button for every sampler is overlapped with the component
Solution: Modified the `top` property of panel's controls to move a little bit more to the top
PLAT-124541

PLAT-124541: Fixed close button position for Panels

---

samples/qa-a11y/src/App/App.js
samples/qa-a11y/src/App/App.module.less

Replace TabbedPanels with Scroller for qa-a11y menu because it is better to search and select a menu.

PLAT-125453: Replace TabbedPanels with Scroller for qa-a11y menu

---

Button/Button.js
Button/Button.module.less
CHANGELOG.md
Keypad/Keypad.js
MediaPlayer/MediaControls.js
ToggleButton/ToggleButton.js
ToggleButton/ToggleButton.module.less

- Added `minwidth=false` for the Buttons inside Keypad, Mediaplayer and ToggleButton
- added different border radius if Button has iconOnly, but minWidth=true
- changed style in ToggleButton from .minWidth to .iconOnly due to the latest architecture change in Button.
PLAT-127764

PLAT-127764: Fix Keypad, MediaPlayer, and ToggleButton to have proper width

---

ArcPicker/ArcPicker.module.less
CHANGELOG.md
FanSpeedControl/FanSpeedControl.module.less
styles/colors-base.less
styles/variables-base.less
styles/variables-gallium.less
styles/variables-silicon.less

- added `font-size` and `font-weight` to `ArcPicker` component to share the same styles as `ArcSlider`
- removed `font-size` style from `FanSpeedControl` as now it inherits it from `ArcPicker`
PLAT-124521

PLAT-124521: Fix the text size in ArcPicker is smaller than the one in ArcSlider

---

CHANGELOG.md
LabeledIconButton/LabeledIconButton.module.less

Revert "PLAT-122792: LabeledIconButton: Huge Icon is cut off. (#376)"
This reverts commit e854b72715ff618e545f4b08edd576cf22a7d072.
Enact-DCO-1.0-Signed-off-by: Jeonghee Ahn (jeonghee27.ahn@lge.com)

Revert "PLAT-122792: LabeledIconButton: Huge Icon is cut off. (#376)"

---

CHANGELOG.md
LabeledIconButton/LabeledIconButton.js

This PR fixes LabledIconButton shape to circular.
And the warning saying 
```
Warning: React does not recognize the `iconOnly` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `icononly` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

PLAT-129803: Fix LabeledIconButton shape to circular

---

CHANGELOG.md
Dropdown/Dropdown.js

Issue: Expanded dropdown is not closed on Escape key press.
Solution: Added `escKeyPressed` function and `handleKeyDown` handler to forward onClick on Toggleable. Pressing Escape closes the dropdown.
PLAT-121900

PLAT-121900: Fix to close expanded dropdown with back(escape) key

---

samples/qa-a11y/src/App/App.module.less

When tapping a menu in qa-a11y sample, the menu below the menu being tapped is selected.
The menu inner DOM element is bigger than the the menu outer DOM element and overlaps over other menus.
For example, a `Dropdown` menu overlaps a `Drawer` menu.
By applying `ponter-events: none` to inner DOM element in the menu,
the `Drorpdown` menu doesn't overlaps the `Drawer` menu anymore.
PLAT-130875

PLAT-130875: qa-a11y> Prevent menu inner DOM elements to handle events

---

CHANGELOG.md
Dropdown/Dropdown.module.less
styles/colors-base.less
styles/colors-silicon-day.less

Issue: agate/Dropdown: The current Silicon Dropdown arrow mark is always red. The user can not see if the dropdown is focused or not with 5-way key.
Solution: Made the dropdown arrow color to have accent color only on focus
PLAT-129910

PLAT-129910: Fixed dropdown button arrow color for Silicon skin

---

Dropdown/Dropdown.js
Dropdown/tests/Dropdown-specs.js

- added extra unit tests for agate/Dropdown
PLAT-129507

PLAT-129507: Add unit tests for Dropdown

---

CHANGELOG.md
MediaPlayer/MediaPlayer.js

Issue: Initial focus is needed when opening dropdown with 5-way key.
Solution: Set current time to 0 when pressing previous button in order to play media from the beginning after being paused.
PLAT-130739

PLAT-130739: Fix previous button to work properly when media paused

---

tests/ui/apps/LabeledIconButton/LabeledIconButton-View.js
tests/ui/specs/LabeledIconButton/LabeledIconButton-specs.js

Remover Scroller from LabeledIconButton-View. Change view layout, updated failed tests. 
The reason was that having the buttons wrapped in Scroller caused this bug. The test that failed intermittently was regarding the first LabeledIconButton that did not fit into the view and to which you had to scroll down to see. I removed the Scroller and positioned buttons with grid layout.
PLAT-132783

PLAT-132783: Fix ui-test fail on LabeledIconButton

---

samples/sampler/stories/qa/Spinner.js

QA sampler for Spinner throws a lint warning after the Agate 2.0.0-alpha.1 release
Removed import of 'React' that cause the lint warning
PLAT-136515

PLAT-136515: Fixed lint warning in qa-sampler for Spinner

---

LabeledIconButton/LabeledIconButton.js
samples/sampler/stories/default/LabeledIconButton.js

https://github.com/enactjs/enact/pull/2902 brought `agate/LabeledIconButton` lost its default size "large" value.
Added default size prop "large" for LabeledIconButton
PLAT-107982

PLAT-107982: Added default size prop for LabeledIconButton

---

CHANGELOG.md
ContextualPopupDecorator/ContextualPopupDecorator.js
Dropdown/Dropdown.module.less
samples/sampler/stories/default/Dropdown.js
samples/sampler/stories/default/Dropdown.module.less
styles/variables-base.less

When the dropdown button is on the extreme left/right of the screen, the contextual popup was not horizontally aligned with the button
Added a margin for Dropdown, to allow the Button and ContextualPopup to be aligned
PLAT-139512

PLAT-139512: Fixed misalignment of Dropdown and ContextualPopup on the edge of screen

---

CHANGELOG.md
styles/variables-base.less
styles/variables-gallium.less
styles/variables-silicon.less

The text-size in TemperatureControl/Arcslider was too small for all skins except Gallium/Silicon
Since there is no official GUI spec for ArcSlider besided Silicon skins, The same values from Silicon were applied to all skins
PLAT-141479

PLAT-141479: Fixed text size for ArcSlider

---

CHANGELOG.md
styles/colors-carbon.less

On Carbon skin, when RadioItem was focused, the border-color of the icon was invisible. I changed the value to @agate-accent to have the same color as text and circle that shows selected state.
PLAT-141638

PLAT-141638: Fixed RadioItem icon border-color for focused state in Carbon skin

---

CHANGELOG.md
styles/colors-base.less

Set buttons section background-color to transparent for all skins, except Silicon. The bug was introduced when Silicon updated its design requirements and had a different background-color for the buttons section.
PLAT-141621

PLAT-141621: Fixed Popup body background-color for other skins than Silicon

---

CHANGELOG.md
styles/colors-carbon.less

On Carbon skin, the text color for the buttons in SliderButton component was hardly visible, so I changed it to a more visible one.
PLAT-141636

PLAT-141636: Fixed SliderButton text color to be more visible on Carbon skin

---

samples/sampler/stories/default/FanSpeedControl.js

The empty string didn't apply to the icon prop in FanSpeedControl sampler.
Since our storybook-utils `select` nullifies the null string, so the empty string couldn't be applied.
Replaced that with the one from @storybook/addon-knobs.
Maybe we need to add some options for not nullifying the value.
PLAT-142521

PLAT-142521: Fix not applying empty string to FanSpeedControl sampler

---

CHANGELOG.md
styles/colors-copper-day.less

When `Copper-day` skin is used in storybook, the text is barely visible, as it has almost the same color as background color. 
Changed text color to be a lighter one. 
PLAT-141477

PLAT-141477: Copper skin text color is not clearly visible

---

tests/screenshot/apps/Agate-View.js

There is screenshot test fail about focus
Set default input-type class for focus.
Fix wrong TC on FormCheckboxItem (regression from #856)
PLAT-143413
Enact-DCO-1.0-Signed-off-by: Jeonghee Ahn (jeonghee27.ahn@lge.com)

PLAT-143413: [Screenshot test] Set default input-type class for focus

---

CHANGELOG.md
Slider/Slider.module.less

Enact-DCO-1.0-Signed-off-by: Juwon Jeong (juwon.jeong@lge.com)
`Slider` knob does not keep activated while dragging by touch.
Apply focus style to slider while dragging by touch. 
PLAT-142797

PLAT-142797: Apply focus styling while dragging slider knob

---

CHANGELOG.md
styles/variables-base.less

The ThumbnailItem and its thumbnail image would not display correctly for skins other than Silicon and Gallium.
Made ThumbnailItem and its thumbnail image display correctly.
PLAT-141486
Enact-DCO-1.0-Signed-off-by: Paul Beldean paul.beldean@lgepartner.com

PLAT-141486: ThumbnailItem - image not visible

---

CHANGELOG.md
Checkbox/Checkbox.module.less
styles/variables-base.less
styles/variables-gallium.less
styles/variables-silicon.less

The checkbox icon size was too small for Carbon/Copper/Cobalt/Electro/Titanium skins compared to its parent container
The color was invisible for Cobalt and Copper skins, on focus.
Added the same icon font-size as in Gallium and Silicon skins. (For Gallium and Silicon the value is changed from 49px to 48px to respect the enact resolution independence rules - multiple of 3)
Changed  @agate-checkbox-size from 46px to 45px to be a multiple of 3 and respect the enact resolution independence rules
Added color for focus state, the same as for normal state, in order to override spottable styles.
[//]: # (How …

PLAT-141485: Fixed checkbox icon size and focus color

---

samples/sampler/stories/default/Popup.js

On Silicon skin, the button/buttons in Popup must be centered at all times. I added an extra story for Popup with 1 button to check this. 
PLAT-144923

PLAT-144923: Popup button must be centered in Silicon skin

---

ContextualPopupDecorator/ContextualPopupDecorator.js

Enact-DCO-1.0-Signed-off-by: Juwon Jeong (juwon.jeong@lge.com)
Fix `direction` prop bleed in `ContextualPopupDecorator`
Delete direction prop before passing it down as props to component
ENYO-6332

ENYO-6332: Fix direction prop bleed in ContextualPopupDecorator

---

CHANGELOG.md
useScroll/ScrollButtons.js

5-way `down` from `up` scrollbar button goes to a list item.
`createRef` returns a new ref on every render so it should be `useRef`.
Removed [] dependency since it needs to be updated when props changed.
PLAT-122723

PLAT-122723: Fix VirtualList 5-way navigation between scroll buttons when `focusableScrollbars`

---

samples/sampler/stories/default/ProgressBar.js

On all skins, in storybook, when orientation was 'vertical', the tooltip was clipped if positioned "left" on LTR and "right" on RTL. I added a margin left and a margin right to the sample to solve the issue.
PLAT-141632

PLAT-141632: Fixed ProgressBar tooltip to not be clipped

---

samples/sampler/.qa-storybook/main.js
samples/sampler/.storybook/main.js

Resolve the warning related to the default PostCSS plugins that deprecated
As logs described, Default PostCSS plugins will be deprecated in the future(Storybook v7.0.0).
> DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.
So we fix the warning via using the below guide. 
(https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-implicit-postcss-loader) …

WRN-3645: Sampler: Default PostCSS plugins are deprecated

---

samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js

Before migrating storybook 6.x, the title of each sample was the same as its story name.
There seems to be a bug when migrating the storybook.
Make the title of each sample the same as the story name.
WRN-2730

WRN-2730: Fix the title of story is the same as the story name in QA sampler

---

.travis.yml
package.json

Requires travis test on multiple node versions including lts
Update .travis.yml so that it can be tested on multiple node versions (lts(16), node(18))
- ubuntu 20 is required for node 18 ( https://docs.travis-ci.com/user/reference/focal/)
- 'npm link' behavior is different between npm6(node14) and npm8(node16,node18) so 'npm install' is done before 'npm link'
WRO-4551

WRO-4551:Update the node version of travis

---

Button/Button.js

Receiving the "className" config on MarqueeDecorator is not our standard way.
Replace 'className' config to `css` for `ui/MarqueeDecorator`
WRO-3940, WRO-608
Enact-DCO-1.0-Signed-off-by: Jeonghee Ahn (jeonghee27.ahn@lge.com)

WRO-3940: Replace `className` config to `css` of ui/MarqueeDecorator

---

CHANGELOG.md

Updated changelog for deprecated `agate/GridListImageItem` to be removed in 2.0.0.
- Deprecate `agate/GridListImageItem` to be removed in 2.0.0.
WRO-2823

WRO-2823: Updated changelog for deprecate `agate/GridListImageItem`

---

samples/sampler/stories/default/Panels.js

Fixed Previous panel does not display when 5-way select button in second panel.
WRO-7974

WRO-7974: Panels: Fixed Previous panel does not display when 5-way select button in second panel.

---

CHANGELOG.md
ThemeDecorator/ThemeDecorator.module.less

Enact-DCO-1.0-Signed-off-by: Alexandru Morariu alexandru.morariu@lgepartner.com
Changed where the background-color and backgroung-image are applied in ThemeDecorator.module.less to mirror the Sandstone changes and apply them properly.
Because of the applied page background color and image the screenshot tests failed and there are differences in the page background of storybook. However there are no layout shifts and no change in the color of the components …

WRO-9305: Enact Browser background color is white when silicon night skin

---

CHANGELOG.md
Scroller/useSpotlight.js

This PR solves a bug on the Scroller component. When focusableScrollbar=true, focusing the bottom button of the vertical scroller and then moving the focus to the right, beside changing the focus to the right button of the horizontal scroller, triggered also a scroll towards the button of the horizontal scroller.
WRO-9302
Enact-DCO-1.0-Signed-off-by: Clapou Vladut [vladut.clapou@lgepartner.com](mailto:vladut.clapou@lgepartner.com) …

WRO-9302: [Scroller]Should not scroll when focus moves paging control to paging control

---

ArcPicker/ArcPicker.js
ArcSlider/ArcSlider.js
CHANGELOG.md
styles/colors-carbon.less
styles/variables-carbon.less

For Carbon skin, there were some issues with some colors for the following components:
- ArcPicker/FanSpeedControl - selected segments not showing
- ArcSlider - Carbon skin - progress and knob not showing
- DatePicker/RangePicker/TimePicker - Carbon skin - text not showing on focus
Changed the default arc/segment color from black to dark grey (since Carbon has black background color on panels). 
Changed focused text color to white for pickers. 
Also added padding to the Panel component as the ArcPicker and ArcSlider samplers were too close to …

WRO-10539: Fixed Carbon skin: text not showing on some components

---

CHANGELOG.md
TemperatureControl/TemperatureControl.js
TemperatureControl/TemperatureControl.module.less
samples/sampler/stories/default/TemperatureControl.js

Enact-DCO-1.0-Signed-off-by: Alexandru Morariu alexandru.morariu@lgepartner.com
Added a css class for the span of the TemperatureControl. The 'unit' prop still has uses to show a programmer how the interval he choses is represented in all the locales so I renamed  it to 'defaultUnitOfMeasurement' to better reflect it's role .
WRO-10538

WRO-10538: Temperature control: Layout issue for locale es-ES and unit selection

---

ArcPicker/ArcPicker.js
ArcSlider/ArcSlider.js
CHANGELOG.md

ui-tests job on jenkins was failing because the foreground color of the component did not match the expectation
Cause of this bug is a previous PR #667 where the color was changed for all skins, not just Carbon skin
Added extra conditions for applying the new foreground color only for carbon skin and maintaining the old black color for the other skins
WRO-10826
Enact-DCO-1.0-Signed-off-by: Daniel Stoian …

WRO-10826: Fixed foreground color for ArcSlider and ArcPicker

---

CHANGELOG.md
samples/sampler/src/ThemeEnvironment/ThemeEnvironment.js
styles/variables-electro.less

On Electro skin the padding of the DatePicker component was not set properly and the component was cropped.
I changed the padding to make the component fully visible on Electro skin.
WRO-11340
Enact-DCO-1.0-Signed-off-by: Andrei Tirla [andrei.tirla@lgepartner.com](mailto:daniel.stoian@lgepartner.com)

WRO-11340: Fixed DatePicker padding on Electro skin

---

samples/qa-a11y/src/views/ImageItem.js
samples/qa-a11y/src/views/VirtualGridList.js
samples/sampler/stories/default/Image.js
samples/sampler/stories/default/ImageItem.js
samples/sampler/stories/default/VirtualGridList.js
samples/sampler/stories/helper/svg.js
samples/sampler/stories/qa/ImageItem.js
tests/screenshot/apps/components/Image.js

There is a problem that image download often fails on the placeholder website used in samples
Instead of downloading the image from the site, change it to create and use the image as svg
WRO-11656

WRO-11656: Change the image used in the sample to svg

---

CHANGELOG.md
Input/InputSpotlightDecorator.js

Cannot select text via double tap
It was side effect from https://github.com/enactjs/agate/pull/354
We should allow default browser behavior when user touch / mouse-down `input` tag.
So I add condition to `preventDefault`
WRO-12023
PLAT-94190
Enact-DCO-1.0-Signed-off-by: Jeonghee Ahn (jeonghee27.ahn@lge.com)

WRO-12023: Allow double tap behavior on Input

---

CHANGELOG.md
IncrementSlider/IncrementSlider.js
Slider/Slider.js
Slider/SliderBehaviorDecorator.js

IncrementSlider sample throws the following warning: "Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?"
Passed sliderRef from SliderBehaviorDecorator to IncrementSlider to Slider.
WRO-13688

WRO-13688: Increment Slider - fix ref console error

---

CHANGELOG.md
IncrementSlider/IncrementSlider.js
Slider/Slider.js
Slider/SliderBehaviorDecorator.js

Reverts enactjs/agate#686
Revert to temporarily except this patch for the Agate release.

Revert "WRO-13688: Increment Slider - fix ref console error"

---

CHANGELOG.md
internal/DateComponentPicker/DateComponentPicker.module.less
internal/Picker/Picker.module.less
styles/variables-base.less
styles/variables-silicon.less

Changed the width/height of the container with className focusBackground. Instead of (100% - a fixed value in px), I calculated a percentage based on the absolute values presented in the UX guide. (example 610/700px = 87% ) https://app.zeplin.io/project/5fab9d1c39e44d926043ec54/screen/60222935a453c3bac7a1778d 
I moved the uneven padding for silicon skin from Picker to the DateComponentPicker. The uneven padding was necesary only in the date and time picker components. 
For Picker and RangePicker it generated an unnecesary uneven position of the text and background focus container, especially when the picker width was the same as the text width.
Ss tests showed a change of text position in Date and Time pickers for …

WRO-14150: Fixed focused background color for Picker when content fits the width

---

Header/Header.js
samples/qa-scroller/src/components/Controls/Controls.js
samples/qa-scroller/src/views/MainView.js
samples/qa-virtuallist/src/views/MainPanel.js

The header of qa-scroller and qa-virtuallist samples is not adapting to the screen width.
Refactored page header styling to work with different type of screen widths.
WRP-3052

WRP-3052: Refactor header for qa-scroller and qa-virtuallist samples

---

TooltipDecorator/tests/TooltipDecorator-specs.js

Increased code coverage for TooltipDecorator from 14.35% to 90.74%.
Code coverage increase
Tooltip.js 83.33% -> 100%
TooltipDecorator.js 7.01% -> 91.22%
utils.js 7.22% -> 87.95%
WRP-3065

WRP-3065: Increase code coverage for TooltipDecorator

---

CHANGELOG.md
Slider/SliderBehaviorDecorator.js

On touchscreen devices, when dragging the slider, an error was thrown in the console
Updated the focusSlider function to read correctly the reference
The fix was debugged on PC ChromeDevTools for mobile device and  on ChromeAndroid
WRP-2681

WRP-2681: SliderBehaviorDecorator - Fixed reading of sliderRef node on touchscreen devices

---

tests/ui/specs/Drawer/Drawer-specs.js
tests/ui/specs/Drawer/DrawerPage.js
tests/ui/specs/SwitchItem/SwitchItem-specs.js
tests/ui/specs/TimePicker/TimePicker-specs.js

Ui tests job on Jenkins for Agate develop branch are failing for Drawer (with scrimType - none should have correct heading) and SwitchItem (pointer should re-select the item when clicked twice).
For Drawer I changed `waitForOpen` and `waitForClose` to be asyncronous. They both use `waitForExist` command from webdriverio which must be used inside async functions (https://webdriver.io/docs/api/element/waitForExist/).
For SwitchItem I refocused the element before selecting it again.
[//]: # (Are there …

WRP-6584: Fixed failed ui tests on Jenkins

---

CHANGELOG.md
SwitchItem/SwitchItem.module.less
styles/colors-base.less
tests/screenshot/apps/components/SwitchItem.js

When a SwitchItem with selected=true, there was no border color for Gallium skin on focus
Fixed border color for selected SwitchItem for Gallium skin by modifying component less styling
WRP-7672
Enact-DCO-1.0-Signed-off-by: Ion Andrusciac (ion.andrusciac@lgepartner.com)

WRP-7672: Fixed border color for selected SwitchItem for Gallium skin

---

useScroll/useScroll.js

`scrollContainerHandle` has a initial object having several properties, but its `current` object is replaced by `setScrollContainerHandle` in the first rendering cycle. So, it looks better to make the initial object empty for better understanding in later visits.
Make the initial object empty, then add comments about properties that should be inside `scrollContainerHandle`.
I found that `scrollPos` does …

WRP-5951: Refine `scrollContainerHandle` of `useScroll` to be clearly understandable

---

ToggleButton/ToggleButton.module.less

On ToggleButton, when underline property is set to "false" and skin=Silicon, the toggle indicator is not visible, but the children remain uncentered
Changed ToggleButton css module to remove the left padding of the children when underline=false but kept it for underline=true.
WRP-9587

WRP-9587: ToggleButton - center the text on Silicon skin when underline=false

---

Input/tests/Input-specs.js

When running unit tests for Agate/Input, some console errors are shown although the tests passed. 
By reordering the problematic tests, we were able to prevent the console errors from being triggered.
We couldn't find the root cause of the problem at this moment, we tried implementing some solutions found online but they did not work and weren't applicable.
WRP-9586
Enact-DCO-1.0-Signed-off-by: Andrei Tirla …

WRP-9586: Fixed "not wrapped in act()" console error for unit tests

---

CHANGELOG.md
MediaPlayer/MediaSlider.module.less
styles/variables-base.less
styles/variables-carbon.less
styles/variables-silicon.less

Fixed MediaPlayer, when type = "tiny" slider knob overlays the text when knob is active and skin is Silicon
The knob was resized in order not to overlay the text
The same problem was found and resolved on the skin Carbon
WRP-9583
Enact-DCO-1.0-Signed-off-by: Ion Andrusciac ion.andrusciac@lgepartner.com

WRP-9583: Fixed MediaPlayer knob on focus for type "tiny" 

---

tests/ui/specs/SwitchItem/SwitchItem-specs.js

Ui tests job on Jenkins for Agate develop branch are failing for  SwitchItem (should re-unselect the item when clicked twice).
Added await for each click in the test suite.
I also added a pause between Page.SpotlightSelect() actions in various tests in order to wait for the transition to end
WRP-12280

WRP-12280: Fixed SwitchItem ui tests

---

CHANGELOG.md
DropManager/DropManager.js
DropManager/tests/DropManager-specs.js

DropManager did not work on touchscreen devices
Added handling for touchStart, touchMove and touchEnd events
There is no drag image on touch events, but the drop area is easily visible, thanks to the already available classnames that are assigned to the  drop areas.
WRP-12450

WRP-12450: Adapted DropManager for touchscreen devices

---

.travis.yml
Arc/tests/Arc-specs.js
Button/tests/Button-specs.js
ColorPicker/tests/ColorPicker-specs.js
ContextualPopupDecorator/tests/ContextualPopupDecorator-specs.js
DatePicker/tests/DatePicker-specs.js
DateTimePicker/tests/DateTimePicker-specs.js
Dropdown/tests/Dropdown-specs.js
IncrementSlider/tests/IncrementSlider-specs.js
Input/tests/Input-specs.js
Keypad/tests/Keypad-specs.js
MediaPlayer/tests/MediaPlayer-specs.js
Panels/tests/Breadcrumb-specs.js
Panels/tests/TabbedPanels-specs.js
Popup/tests/Popup-specs.js
RadioItem/tests/RadioItem-specs.js
RangePicker/tests/RangePicker-specs.js
Scroller/tests/Scroller-specs.js
TabGroup/tests/TabGroup-specs.js
TimePicker/tests/TimePicker-specs.js
internal/Picker/tests/Picker-specs.js

@testing-library/user-event version 14 introduced API changes so we need to update unit tests.
Updated tests that are using @testing-library/user-event module.
TBD
This PR should be merged after @enact/cli 6.0.0 is released, otherwise, Travis will be broken.
WRP-15107

WRP-15107: Update unit tests to work with @testing-library/user-event 14

---

Panels/Panels.module.less
samples/sampler/stories/default/Panels.js
samples/sampler/stories/qa/Panels.js
styles/variables-carbon.less
tests/screenshot/apps/components/Panels.js

Added missing prop `cover` from storybook.
Applied the required css for the prop value `partial`.
Panels now displays the prop `cover` on storybook with the required css.
WRP-21123

WRP-21123: Added missing prop from sampler and applied the required css

---

samples/qa-a11y/src/views/ReadAlert.js

`PalmServiceBridge` was renamed as `WebOSServiceBridge` in 2018 with an fallback alias for compatibility on legacy webOS.
Updated qa-a11y sample to use `WebOSServiceBridge`
WRP-26268

WRP-26268: Rename PalmServiceBridge as WebOSServiceBridge

---

samples/qa-a11y/src/views/ReadAlert.js

Fixed audio guidance to work when `Audio Guidance` button is checked
WRP-27419

WRP-27419: A11y - ReadAlert - There is no readalert when checking togglebutton

---

.travis.yml
ContextualPopupDecorator/ContextualPopupDecorator.js
Dropdown/Dropdown.js
Dropdown/DropdownList.js
tests/screenshot/apps/components/Dropdown.js

Opened dropdown is not adapted by direction in a certain skin of Agate Dropdown.
I added 'onAdjustDirection' Changeable function and 'adjustedDirection' property to Dropdown.
'adjustedDirection' fixes the direction of the opened dropdown. 
WRQ-2635
Enact-DCO-1.0-Signed-off-by: Jiye Kim ([jiye.kim@lge.com](mailto:jiye.kim@lge.com))

WRQ-2635: [Agate] Dropdown: Dropdown is not adapted by direction.

---

Scroller/Scroller.js
VirtualList/VirtualList.js

The default value of `scrollMode` prop in `Scroller` and `VirtualList` was changed from 'translate' to 'native' in #748, but we missed to update JSDoc for it.
WRQ-7452

WRQ-7452: fixed JSDoc for `scrollMode` prop of `Scroller` and `VirtualList`

---

ColorPicker/tests/ColorPicker-specs.js
MediaPlayer/tests/MediaPlayer-specs.js
Panels/Panels.module.less
TabGroup/tests/TabGroup-specs.js

As DOM structure of ui/Spottable is updated in enactjs/enact/pull/3243, the corresponding internal style sheet needs to be updated.
Updated the related styles.
Also, unit tests for ColorPicker, MediaPlayer, and TabGroup are updated due to DOM structure changes.
WRQ-19325
enactjs/enact/pull/3243

WRQ-19325: Updated Panels' Header to work with changed DOM structure of Spottable

---

.travis.yml
Marquee/Marquee.js

Fix `Marquee` to not override `marqueeDirection`(that code moved to `@enact/ui/Marquee.MarqueeDecorator`)
Remove `marqueeDirection` override in `Marquee`
WRQ-17541
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong (taeyoung.hong@lge.com)

WRQ-17541: Fix Marquee to not override marqueeDirection

---

.travis.yml

travis error occurs due to a lot of console warnings.
https://github.com/enactjs/agate/runs/27537930727 
we checked this error does not occur with cli master branch,
so we change cli branch in travis.yml file to master temporarily.
after fixing the problem, we should revert the branch.
WRQ-29884
Enact-DCO-1.0-Signed-off-by: Jiye Kim (jiye.kim@lge.com)

WRQ-29884: Change cli branch in travis.yml to master

---

ArcPicker/ArcPickerBehaviorDecorator.js
Slider/SliderBehaviorDecorator.js
SliderButton/SliderButtonBehaviorDecorator.js
useScroll/useScroll.js

"platform.touchscreen" is removed in enact 5.0.0
Replaced deprecated `platform.touchscreen` with `platform.touchScreen` available in @enact/core/platform.
WRQ- 30259

WRQ- 30259: Replaced deprecated `platform.touchscreen` with `platform.touchScreen`

---

CHANGELOG.md
ToggleButton/ToggleButton.module.less
styles/variables-base.less
styles/variables-carbon.less
styles/variables-electro.less
styles/variables-gallium.less
styles/variables-silicon.less
styles/variables-titanium.less
tests/screenshot/apps/components/ToggleButton.js

Fix ToggleButton underline position
Fix ToggleButton underline position
WRQ-29377
Enact-DCO-1.0-Signed-off-by: Paul Beldean paul.beldean@lgepartner.com

WRQ-29377: Fix ToggleButton underline position

---

.travis.yml
CHANGELOG.md
Scroller/Scroller.js
VirtualList/VirtualList.js

Enact-DCO-1.0-Signed-off-by: Juwon Jeong (juwon.jeong@lge.com)
In https://github.com/enactjs/agate/pull/786, we removed defaultProps and implemeted this feature manually.
After this implementation, if `undefined` is passed for a prop value, the prop value remains undefined.
However, defaultProps(https://legacy.reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values) sets prop value to default value when undefined value is passed for the prop.
Fix `Scroller`, `VirtualList` and `VirtualGridList` to set prop value to default value when undefined is passed for the prop value
[//]: # (How should …

WRQ-31515: Fixed Scroller and VirtualList to set prop value to default value when `undefined` is passed for the prop value

---

samples/sampler/.qa-storybook/manager.js
samples/sampler/.storybook/manager.js

Enact-DCO-1.0-Signed-off-by: Dongsu Won (dongsu.won@lgepartner.com)
The height of addons bottom panel has changed as the storybook has been updated to 8.0.
So we need to fix height of addons bottom panel.
Fix height of addons bottom panel.
This PR is basically the same with https://github.com/enactjs/sandstone/pull/1666.
WRR-394

WRR-394: Update default height of bottom pannel in agate storybook

---

samples/sampler/npm-shrinkwrap.json
samples/sampler/package.json

There are some unused modules in sampler.
Removed unused modules: `@storybook/builder-webpack5`, `@storybook/react` and `babel-loader`.
**@storybook/builder-webpack5**: 
- added in 2022 when updating to Storybook 6.5 and webpack 5, but with Storybook 8 `@storybook/builder-webpack5` became part of storybook/react-webpack5, so it can be removed (https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#new-framework-api)
**@storybook/react**: 
- added in 2020 …

WRR-7148: Removed unused modules in sampler

---

LabeledIconButton/LabeledIconButton.module.less
ThemeDecorator/ThemeDecorator.module.less
internal/Picker/Picker.module.less

Some components are using enact/ui's .vendor-opacity() mixin but we don't need it. We normally use the standard opacity CSS attribute and just two components are using the mixin as their code is copied from the old codebase.
Replace .vendor-opacity() mixin with the standard opacity CSS attribute.
WRR-9415

WRR-9415: Replace .vendor-opacity mixin with the standard opacity attribute

---

Item/Item.js
SliderButton/SliderButton.js
VirtualList/useThemeVirtualList.js
samples/qa-a11y/src/views/Panels.js
samples/qa-a11y/src/views/VirtualGridList.js
samples/qa-a11y/src/views/VirtualList.js
samples/sampler/stories/default/VirtualGridList.js
samples/sampler/stories/default/VirtualList.js

https://ko.react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-deprecated-react-apis
PropTypes were deprecated in April 2017 (v15.5.0).
However, the enact/prop-types rule still exists, so removing PropType causes a linting error.
Remove unused eslint-disable directive 'enact/prop-types'
WRR-23385
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong (taeyoung.hong@lge.com)

WRR-23385: Remove unused eslint-disable directive 'enact/prop-types'
